-- 038_item_pricing_setup.sql
-- Phase 1 foundation for CAP Item Pricing Setup.
-- Source pricing model: Blank EQP 2500+ is stored as the item base price.
-- Flat EQP = Blank EQP + 3.00.
-- 3D EQP = Blank EQP + 5.75, calculated directly from Blank EQP.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.item_pricing_price_books (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL,
  name text NOT NULL,
  description text NULL,
  status text NOT NULL DEFAULT 'DRAFT',
  effective_date date NULL,
  expiration_date date NULL,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text NULL,
  is_voided boolean NOT NULL DEFAULT false,
  voided_at timestamptz NULL,
  voided_by text NULL,
  void_reason text NULL,
  CONSTRAINT item_pricing_price_books_status_chk
    CHECK (status IN ('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED')),
  CONSTRAINT item_pricing_price_books_dates_chk
    CHECK (expiration_date IS NULL OR effective_date IS NULL OR expiration_date >= effective_date)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_item_pricing_price_books_code_active
  ON public.item_pricing_price_books (upper(code))
  WHERE is_voided = false;

CREATE UNIQUE INDEX IF NOT EXISTS ux_item_pricing_price_books_default_active
  ON public.item_pricing_price_books (is_default)
  WHERE is_default = true AND is_voided = false;

CREATE TABLE IF NOT EXISTS public.item_pricing_rule_sets (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text NULL,
  allows_blank boolean NOT NULL DEFAULT true,
  allows_flat_emb boolean NOT NULL DEFAULT true,
  allows_3d_emb boolean NOT NULL DEFAULT false,
  allows_knit_in boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text NULL
);

CREATE TABLE IF NOT EXISTS public.item_pricing_decoration_methods (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text NULL,
  sort_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text NULL,
  CONSTRAINT item_pricing_decoration_methods_code_chk
    CHECK (code IN ('BLANK', 'FLAT_EMB', 'THREE_D_EMB', 'KNIT_IN'))
);

CREATE TABLE IF NOT EXISTS public.item_pricing_quantity_breaks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  label text NOT NULL,
  min_qty integer NOT NULL,
  max_qty integer NULL,
  sort_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text NULL,
  CONSTRAINT item_pricing_quantity_breaks_qty_chk
    CHECK (min_qty > 0 AND (max_qty IS NULL OR max_qty >= min_qty))
);

CREATE TABLE IF NOT EXISTS public.item_pricing_rule_set_breaks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  rule_set_id integer NOT NULL REFERENCES public.item_pricing_rule_sets(id) ON DELETE CASCADE,
  decoration_method_id integer NOT NULL REFERENCES public.item_pricing_decoration_methods(id),
  quantity_break_id integer NOT NULL REFERENCES public.item_pricing_quantity_breaks(id),
  base_reference text NOT NULL,
  prior_quantity_break_id integer NULL REFERENCES public.item_pricing_quantity_breaks(id),
  adder_amount numeric(12, 4) NOT NULL DEFAULT 0,
  calculation_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  notes text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text NULL,
  CONSTRAINT item_pricing_rule_set_breaks_base_ref_chk
    CHECK (base_reference IN ('BLANK_EQP', 'FLAT_EQP', 'THREE_D_EQP', 'PRIOR_BREAK', 'KNIT_IN_EQP')),
  CONSTRAINT item_pricing_rule_set_breaks_prior_chk
    CHECK (
      (base_reference = 'PRIOR_BREAK' AND prior_quantity_break_id IS NOT NULL)
      OR (base_reference <> 'PRIOR_BREAK')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_item_pricing_rule_set_breaks_active
  ON public.item_pricing_rule_set_breaks (rule_set_id, decoration_method_id, quantity_break_id)
  WHERE active = true;

CREATE INDEX IF NOT EXISTS ix_item_pricing_rule_set_breaks_rule_set
  ON public.item_pricing_rule_set_breaks (rule_set_id, decoration_method_id, calculation_order);

CREATE TABLE IF NOT EXISTS public.item_pricing_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  item_code text NOT NULL,
  item_description text NULL,
  product_family text NULL,
  rule_set_id integer NOT NULL REFERENCES public.item_pricing_rule_sets(id),
  active boolean NOT NULL DEFAULT true,
  allows_blank_override boolean NULL,
  allows_flat_emb_override boolean NULL,
  allows_3d_emb_override boolean NULL,
  allows_knit_in_override boolean NULL,
  notes text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text NULL,
  is_voided boolean NOT NULL DEFAULT false,
  voided_at timestamptz NULL,
  voided_by text NULL,
  void_reason text NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_item_pricing_items_code_active
  ON public.item_pricing_items (upper(item_code))
  WHERE is_voided = false;

CREATE INDEX IF NOT EXISTS ix_item_pricing_items_rule_set
  ON public.item_pricing_items (rule_set_id, active, is_voided);

CREATE TABLE IF NOT EXISTS public.item_pricing_item_base_prices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  price_book_id uuid NOT NULL REFERENCES public.item_pricing_price_books(id) ON DELETE CASCADE,
  item_id uuid NOT NULL REFERENCES public.item_pricing_items(id) ON DELETE CASCADE,
  blank_eqp_price numeric(12, 4) NOT NULL,
  source_file_name text NULL,
  source_sheet_name text NULL,
  source_row_number integer NULL,
  notes text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text NULL,
  CONSTRAINT item_pricing_item_base_prices_blank_chk
    CHECK (blank_eqp_price >= 0),
  CONSTRAINT item_pricing_item_base_prices_source_row_chk
    CHECK (source_row_number IS NULL OR source_row_number > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_item_pricing_item_base_prices_book_item
  ON public.item_pricing_item_base_prices (price_book_id, item_id);

CREATE INDEX IF NOT EXISTS ix_item_pricing_item_base_prices_item
  ON public.item_pricing_item_base_prices (item_id);

CREATE TABLE IF NOT EXISTS public.item_pricing_calculated_prices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  price_book_id uuid NOT NULL REFERENCES public.item_pricing_price_books(id) ON DELETE CASCADE,
  item_id uuid NOT NULL REFERENCES public.item_pricing_items(id) ON DELETE CASCADE,
  rule_set_id integer NOT NULL REFERENCES public.item_pricing_rule_sets(id),
  decoration_method_id integer NOT NULL REFERENCES public.item_pricing_decoration_methods(id),
  quantity_break_id integer NOT NULL REFERENCES public.item_pricing_quantity_breaks(id),
  blank_eqp_price numeric(12, 4) NOT NULL,
  calculated_price numeric(12, 4) NOT NULL,
  calculation_trace jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text NULL,
  CONSTRAINT item_pricing_calculated_prices_amounts_chk
    CHECK (blank_eqp_price >= 0 AND calculated_price >= 0)
);

CREATE INDEX IF NOT EXISTS ix_item_pricing_calculated_prices_book_item
  ON public.item_pricing_calculated_prices (price_book_id, item_id, decoration_method_id, quantity_break_id);

/* -------------------------------------------------------------------------- */
/* Seed setup data                                                             */
/* -------------------------------------------------------------------------- */

INSERT INTO public.item_pricing_price_books (
  code, name, description, status, is_default, created_by, updated_by
)
VALUES (
  '2026_WORKING',
  '2026 Working Price Book',
  'Initial working price book for Phase 1 Item Pricing Setup.',
  'DRAFT',
  true,
  'system',
  'system'
)
ON CONFLICT DO NOTHING;

INSERT INTO public.item_pricing_rule_sets (
  code, name, description, allows_blank, allows_flat_emb, allows_3d_emb, allows_knit_in, sort_order, created_by, updated_by
)
VALUES
  ('IN_STOCK_CAPS', 'In Stock Caps', 'Core in-stock cap pricing family.', true, true, true, false, 10, 'system', 'system'),
  ('PREMIUM_LINE', 'Premium Line', 'Premium Line pricing family. Decorated pricing includes the 15 quantity break.', true, true, true, false, 20, 'system', 'system'),
  ('PREMIUM_LINE_KNITS', 'Premium Line Knits', 'Premium Line knit exception family. No 3D pricing.', true, true, false, false, 30, 'system', 'system'),
  ('IN_STOCK_IMPORT_KNITS', 'In Stock Import Knits / IKs', 'IK in-stock import knit pricing family. No 3D configured in Phase 1.', true, true, false, false, 40, 'system', 'system'),
  ('IN_STOCK_MADE_USA_KNITS', 'In Stock Made in USA Knits / RKs', 'RK made-in-USA knit pricing family. No 3D configured in Phase 1.', true, true, false, false, 50, 'system', 'system'),
  ('ELITE_KNITS', 'Elite Knits', 'Elite Knit-In pricing family.', false, false, false, true, 60, 'system', 'system')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  allows_blank = EXCLUDED.allows_blank,
  allows_flat_emb = EXCLUDED.allows_flat_emb,
  allows_3d_emb = EXCLUDED.allows_3d_emb,
  allows_knit_in = EXCLUDED.allows_knit_in,
  sort_order = EXCLUDED.sort_order,
  updated_at = now(),
  updated_by = 'system';

INSERT INTO public.item_pricing_decoration_methods (
  code, name, description, sort_order, created_by, updated_by
)
VALUES
  ('BLANK', 'Blank', 'Blank item pricing.', 10, 'system', 'system'),
  ('FLAT_EMB', 'Flat Embroidery', 'Flat embroidery pricing. Flat EQP = Blank EQP + 3.00.', 20, 'system', 'system'),
  ('THREE_D_EMB', '3D Embroidery', '3D embroidery pricing. 3D EQP = Blank EQP + 5.75.', 30, 'system', 'system'),
  ('KNIT_IN', 'Knit In', 'Elite knit-in pricing method.', 40, 'system', 'system')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  updated_at = now(),
  updated_by = 'system';

INSERT INTO public.item_pricing_quantity_breaks (
  code, label, min_qty, max_qty, sort_order, created_by, updated_by
)
VALUES
  ('1_23', '1–23', 1, 23, 10, 'system', 'system'),
  ('15', '15', 15, 23, 15, 'system', 'system'),
  ('24', '24', 24, 47, 20, 'system', 'system'),
  ('48', '48', 48, 95, 30, 'system', 'system'),
  ('96', '96', 96, 143, 40, 'system', 'system'),
  ('144', '144', 144, 575, 50, 'system', 'system'),
  ('576', '576', 576, 2499, 60, 'system', 'system'),
  ('2500', '2500+', 2500, NULL, 70, 'system', 'system')
ON CONFLICT (code) DO UPDATE SET
  label = EXCLUDED.label,
  min_qty = EXCLUDED.min_qty,
  max_qty = EXCLUDED.max_qty,
  sort_order = EXCLUDED.sort_order,
  updated_at = now(),
  updated_by = 'system';

-- Structured calculation rule seeds.
-- calculation_order is dependency order, not display order.
WITH seed(rule_set_code, method_code, qty_code, base_reference, prior_qty_code, adder_amount, calculation_order, notes) AS (
  VALUES
    -- In Stock Caps
    ('IN_STOCK_CAPS','BLANK','2500','BLANK_EQP',NULL,0.00,10,NULL),
    ('IN_STOCK_CAPS','BLANK','576','BLANK_EQP',NULL,0.10,20,NULL),
    ('IN_STOCK_CAPS','BLANK','144','BLANK_EQP',NULL,0.20,30,NULL),
    ('IN_STOCK_CAPS','BLANK','96','BLANK_EQP',NULL,0.30,40,NULL),
    ('IN_STOCK_CAPS','BLANK','48','BLANK_EQP',NULL,0.40,50,NULL),
    ('IN_STOCK_CAPS','BLANK','24','BLANK_EQP',NULL,1.50,60,NULL),
    ('IN_STOCK_CAPS','BLANK','1_23','PRIOR_BREAK','24',0.75,70,'1–23 = Blank 24 + 0.75'),
    ('IN_STOCK_CAPS','FLAT_EMB','2500','BLANK_EQP',NULL,3.00,10,'Flat EQP = Blank EQP + 3.00'),
    ('IN_STOCK_CAPS','FLAT_EMB','576','FLAT_EQP',NULL,0.10,20,NULL),
    ('IN_STOCK_CAPS','FLAT_EMB','144','FLAT_EQP',NULL,0.20,30,NULL),
    ('IN_STOCK_CAPS','FLAT_EMB','96','FLAT_EQP',NULL,0.30,40,NULL),
    ('IN_STOCK_CAPS','FLAT_EMB','48','FLAT_EQP',NULL,0.40,50,NULL),
    ('IN_STOCK_CAPS','FLAT_EMB','24','FLAT_EQP',NULL,1.50,60,NULL),
    ('IN_STOCK_CAPS','THREE_D_EMB','2500','BLANK_EQP',NULL,5.75,10,'3D EQP = Blank EQP + 5.75'),
    ('IN_STOCK_CAPS','THREE_D_EMB','576','THREE_D_EQP',NULL,0.10,20,NULL),
    ('IN_STOCK_CAPS','THREE_D_EMB','144','THREE_D_EQP',NULL,0.20,30,NULL),
    ('IN_STOCK_CAPS','THREE_D_EMB','96','THREE_D_EQP',NULL,0.30,40,NULL),
    ('IN_STOCK_CAPS','THREE_D_EMB','48','THREE_D_EQP',NULL,0.40,50,NULL),
    ('IN_STOCK_CAPS','THREE_D_EMB','24','THREE_D_EQP',NULL,1.50,60,NULL),

    -- Premium Line
    ('PREMIUM_LINE','BLANK','2500','BLANK_EQP',NULL,0.00,10,NULL),
    ('PREMIUM_LINE','BLANK','576','BLANK_EQP',NULL,0.10,20,NULL),
    ('PREMIUM_LINE','BLANK','144','BLANK_EQP',NULL,0.20,30,NULL),
    ('PREMIUM_LINE','BLANK','96','BLANK_EQP',NULL,0.30,40,NULL),
    ('PREMIUM_LINE','BLANK','48','BLANK_EQP',NULL,0.40,50,NULL),
    ('PREMIUM_LINE','BLANK','24','BLANK_EQP',NULL,1.00,60,NULL),
    ('PREMIUM_LINE','BLANK','1_23','PRIOR_BREAK','24',0.75,70,'1–23 = Blank 24 + 0.75'),
    ('PREMIUM_LINE','FLAT_EMB','2500','BLANK_EQP',NULL,3.00,10,'Flat EQP = Blank EQP + 3.00'),
    ('PREMIUM_LINE','FLAT_EMB','576','FLAT_EQP',NULL,0.10,20,NULL),
    ('PREMIUM_LINE','FLAT_EMB','144','FLAT_EQP',NULL,0.20,30,NULL),
    ('PREMIUM_LINE','FLAT_EMB','96','FLAT_EQP',NULL,0.30,40,NULL),
    ('PREMIUM_LINE','FLAT_EMB','48','FLAT_EQP',NULL,0.40,50,NULL),
    ('PREMIUM_LINE','FLAT_EMB','24','FLAT_EQP',NULL,1.00,60,NULL),
    ('PREMIUM_LINE','FLAT_EMB','15','FLAT_EQP',NULL,1.10,70,NULL),
    ('PREMIUM_LINE','THREE_D_EMB','2500','BLANK_EQP',NULL,5.75,10,'3D EQP = Blank EQP + 5.75'),
    ('PREMIUM_LINE','THREE_D_EMB','576','THREE_D_EQP',NULL,0.10,20,NULL),
    ('PREMIUM_LINE','THREE_D_EMB','144','THREE_D_EQP',NULL,0.20,30,NULL),
    ('PREMIUM_LINE','THREE_D_EMB','96','THREE_D_EQP',NULL,0.30,40,NULL),
    ('PREMIUM_LINE','THREE_D_EMB','48','THREE_D_EQP',NULL,0.40,50,NULL),
    ('PREMIUM_LINE','THREE_D_EMB','24','THREE_D_EQP',NULL,1.00,60,NULL),
    ('PREMIUM_LINE','THREE_D_EMB','15','THREE_D_EQP',NULL,1.10,70,NULL),

    -- Premium Line Knits: same base family as Premium Line, no 3D rows.
    ('PREMIUM_LINE_KNITS','BLANK','2500','BLANK_EQP',NULL,0.00,10,NULL),
    ('PREMIUM_LINE_KNITS','BLANK','576','BLANK_EQP',NULL,0.10,20,NULL),
    ('PREMIUM_LINE_KNITS','BLANK','144','BLANK_EQP',NULL,0.20,30,NULL),
    ('PREMIUM_LINE_KNITS','BLANK','96','BLANK_EQP',NULL,0.30,40,NULL),
    ('PREMIUM_LINE_KNITS','BLANK','48','BLANK_EQP',NULL,0.40,50,NULL),
    ('PREMIUM_LINE_KNITS','BLANK','24','BLANK_EQP',NULL,1.00,60,NULL),
    ('PREMIUM_LINE_KNITS','BLANK','1_23','PRIOR_BREAK','24',0.75,70,'1–23 = Blank 24 + 0.75'),
    ('PREMIUM_LINE_KNITS','FLAT_EMB','2500','BLANK_EQP',NULL,3.00,10,'Flat EQP = Blank EQP + 3.00'),
    ('PREMIUM_LINE_KNITS','FLAT_EMB','576','FLAT_EQP',NULL,0.10,20,NULL),
    ('PREMIUM_LINE_KNITS','FLAT_EMB','144','FLAT_EQP',NULL,0.20,30,NULL),
    ('PREMIUM_LINE_KNITS','FLAT_EMB','96','FLAT_EQP',NULL,0.30,40,NULL),
    ('PREMIUM_LINE_KNITS','FLAT_EMB','48','FLAT_EQP',NULL,0.40,50,NULL),
    ('PREMIUM_LINE_KNITS','FLAT_EMB','24','FLAT_EQP',NULL,1.00,60,NULL),
    ('PREMIUM_LINE_KNITS','FLAT_EMB','15','FLAT_EQP',NULL,1.10,70,NULL),

    -- IKs / In Stock Import Knits: no 3D rows in Phase 1.
    ('IN_STOCK_IMPORT_KNITS','BLANK','2500','BLANK_EQP',NULL,0.00,10,NULL),
    ('IN_STOCK_IMPORT_KNITS','BLANK','576','BLANK_EQP',NULL,0.10,20,NULL),
    ('IN_STOCK_IMPORT_KNITS','BLANK','144','BLANK_EQP',NULL,0.20,30,NULL),
    ('IN_STOCK_IMPORT_KNITS','BLANK','96','BLANK_EQP',NULL,0.30,40,NULL),
    ('IN_STOCK_IMPORT_KNITS','BLANK','48','BLANK_EQP',NULL,0.40,50,NULL),
    ('IN_STOCK_IMPORT_KNITS','BLANK','24','BLANK_EQP',NULL,1.50,60,NULL),
    ('IN_STOCK_IMPORT_KNITS','BLANK','1_23','PRIOR_BREAK','24',0.75,70,'1–23 = Blank 24 + 0.75'),
    ('IN_STOCK_IMPORT_KNITS','FLAT_EMB','2500','BLANK_EQP',NULL,3.00,10,'Flat EQP = Blank EQP + 3.00'),
    ('IN_STOCK_IMPORT_KNITS','FLAT_EMB','576','FLAT_EQP',NULL,0.10,20,NULL),
    ('IN_STOCK_IMPORT_KNITS','FLAT_EMB','144','FLAT_EQP',NULL,0.20,30,NULL),
    ('IN_STOCK_IMPORT_KNITS','FLAT_EMB','96','FLAT_EQP',NULL,0.30,40,NULL),
    ('IN_STOCK_IMPORT_KNITS','FLAT_EMB','48','FLAT_EQP',NULL,0.40,50,NULL),
    ('IN_STOCK_IMPORT_KNITS','FLAT_EMB','24','FLAT_EQP',NULL,1.50,60,NULL),

    -- RKs / In Stock Made in USA Knits: no 3D rows in Phase 1.
    ('IN_STOCK_MADE_USA_KNITS','BLANK','2500','BLANK_EQP',NULL,0.00,10,NULL),
    ('IN_STOCK_MADE_USA_KNITS','BLANK','576','BLANK_EQP',NULL,0.10,20,NULL),
    ('IN_STOCK_MADE_USA_KNITS','BLANK','144','BLANK_EQP',NULL,0.20,30,NULL),
    ('IN_STOCK_MADE_USA_KNITS','BLANK','96','BLANK_EQP',NULL,0.30,40,NULL),
    ('IN_STOCK_MADE_USA_KNITS','BLANK','48','BLANK_EQP',NULL,1.50,50,NULL),
    ('IN_STOCK_MADE_USA_KNITS','BLANK','24','BLANK_EQP',NULL,2.00,60,NULL),
    ('IN_STOCK_MADE_USA_KNITS','BLANK','1_23','PRIOR_BREAK','24',0.75,70,'1–23 = Blank 24 + 0.75'),
    ('IN_STOCK_MADE_USA_KNITS','FLAT_EMB','2500','BLANK_EQP',NULL,3.00,10,'Flat EQP = Blank EQP + 3.00'),
    ('IN_STOCK_MADE_USA_KNITS','FLAT_EMB','576','FLAT_EQP',NULL,0.10,20,NULL),
    ('IN_STOCK_MADE_USA_KNITS','FLAT_EMB','144','FLAT_EQP',NULL,0.20,30,NULL),
    ('IN_STOCK_MADE_USA_KNITS','FLAT_EMB','96','FLAT_EQP',NULL,0.30,40,NULL),
    ('IN_STOCK_MADE_USA_KNITS','FLAT_EMB','48','FLAT_EQP',NULL,1.50,50,NULL),
    ('IN_STOCK_MADE_USA_KNITS','FLAT_EMB','24','FLAT_EQP',NULL,2.00,60,NULL),

    -- Elite Knits: knit-in only.
    ('ELITE_KNITS','KNIT_IN','2500','KNIT_IN_EQP',NULL,0.00,10,NULL),
    ('ELITE_KNITS','KNIT_IN','576','KNIT_IN_EQP',NULL,0.10,20,NULL),
    ('ELITE_KNITS','KNIT_IN','144','KNIT_IN_EQP',NULL,0.20,30,NULL),
    ('ELITE_KNITS','KNIT_IN','96','KNIT_IN_EQP',NULL,0.30,40,NULL),
    ('ELITE_KNITS','KNIT_IN','48','KNIT_IN_EQP',NULL,1.50,50,NULL),
    ('ELITE_KNITS','KNIT_IN','24','KNIT_IN_EQP',NULL,3.00,60,NULL)
)
INSERT INTO public.item_pricing_rule_set_breaks (
  rule_set_id,
  decoration_method_id,
  quantity_break_id,
  base_reference,
  prior_quantity_break_id,
  adder_amount,
  calculation_order,
  active,
  notes,
  created_by,
  updated_by
)
SELECT
  rs.id,
  dm.id,
  qb.id,
  seed.base_reference,
  prior_qb.id,
  seed.adder_amount,
  seed.calculation_order,
  true,
  seed.notes,
  'system',
  'system'
FROM seed
JOIN public.item_pricing_rule_sets rs
  ON rs.code = seed.rule_set_code
JOIN public.item_pricing_decoration_methods dm
  ON dm.code = seed.method_code
JOIN public.item_pricing_quantity_breaks qb
  ON qb.code = seed.qty_code
LEFT JOIN public.item_pricing_quantity_breaks prior_qb
  ON prior_qb.code = seed.prior_qty_code
WHERE NOT EXISTS (
  SELECT 1
  FROM public.item_pricing_rule_set_breaks existing
  WHERE existing.rule_set_id = rs.id
    AND existing.decoration_method_id = dm.id
    AND existing.quantity_break_id = qb.id
    AND existing.active = true
);
