export const EXTERNAL_MODULE_KEYS = {
  DESIGN_WORKFLOW: "design_workflow",
} as const;

export type ExternalModuleKey =
  (typeof EXTERNAL_MODULE_KEYS)[keyof typeof EXTERNAL_MODULE_KEYS];

export const EXTERNAL_PARTNER_TYPES = {
  WORKFLOW_DESIGN: "WORKFLOW_DESIGN",
  WORKFLOW_DIGITIZING: "WORKFLOW_DIGITIZING",
  PRODUCTION: "PRODUCTION",
} as const;

export type ExternalPartnerType =
  (typeof EXTERNAL_PARTNER_TYPES)[keyof typeof EXTERNAL_PARTNER_TYPES];

export const EXTERNAL_ROLES = {
  EXTERNAL_DESIGNER: "EXTERNAL_DESIGNER",
  EXTERNAL_DIGITIZER: "EXTERNAL_DIGITIZER",
  EXTERNAL_WORKFLOW_PARTNER: "EXTERNAL_WORKFLOW_PARTNER",
  EXTERNAL_VIEWER: "EXTERNAL_VIEWER",
} as const;

export type ExternalRole = (typeof EXTERNAL_ROLES)[keyof typeof EXTERNAL_ROLES];

export const EXTERNAL_PARTNER_CODES = {
  DCX: "DCX",
  OFFICE_BEACON: "OFFICE_BEACON",
  SIGN_DIGITIZING: "SIGN_DIGITIZING",
} as const;

export const EXTERNAL_WORKFLOW_STATUS_CODES = {
  INSTOCK_CONCEPTS: "INSTOCK_CONCEPTS",
  ART_DEPT_PROOFING: "ART_DEPT_PROOFING",
  SIGN_IN_PROGRESS: "SIGN_IN_PROGRESS",
  SIGN_FINISHED: "SIGN_FINISHED",

  A_PO_TO_ART_DEPT: "A",
  RA_REVISIONS: "RA",
} as const;