// lib/reports/recutReportTemplates.ts

import type { ReportAggregateFunction, ReportAggregation } from "./reportTypes";
import type { ReportTemplate } from "./reportTemplates";

function agg(
  column: string,
  fn: ReportAggregateFunction,
  label?: string
): ReportAggregation {
  return {
    column,
    function: fn,
    label,
  };
}

export const RECUT_REPORT_TEMPLATES: ReportTemplate[] = [
  {
    key: "recutSummaryByOperator",
    label: "Recut Summary by Operator",
    description:
      "Recut counts and pieces grouped by assigned operator. Good for reviewing where recuts are being assigned and completed.",
    category: "recuts",
    datasetKey: "recutActivity",
    defaultColumns: ["operator", "recut_id", "pieces", "hours_to_complete"],
    defaultDateColumn: "requested_date",
    defaultDatePreset: "last30Days",
    defaultSort: {
      column: "operator",
      direction: "asc",
    },
    defaultGrouping: ["operator"],
    defaultAggregations: [
      agg("recut_id", "count", "Recut Count"),
      agg("pieces", "sum", "Total Pieces"),
      agg("hours_to_complete", "avg", "Average Hours to Complete"),
    ],
    defaultVisualization: "bar",
    simpleFilters: [
      "operator",
      "requested_department",
      "recut_status",
      "recut_reason",
      "sales_order_display",
    ],
    summaryCards: [
      {
        key: "recuts",
        label: "Recuts",
        sourceColumn: "count_recut_id",
        function: "sum",
        format: "number",
      },
      {
        key: "pieces",
        label: "Pieces",
        sourceColumn: "sum_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "operators",
        label: "Operators",
        sourceColumn: "operator",
        function: "countDistinct",
        format: "number",
      },
      {
        key: "avgComplete",
        label: "Avg Hours to Complete",
        sourceColumn: "avg_hours_to_complete",
        function: "avg",
        format: "hours",
      },
    ],
  },

  {
    key: "recutSummaryByReason",
    label: "Recut Summary by Reason",
    description:
      "Recut counts and pieces grouped by reason. Good for understanding the most common causes of recuts.",
    category: "recuts",
    datasetKey: "recutActivity",
    defaultColumns: ["recut_reason", "recut_id", "pieces", "hours_open"],
    defaultDateColumn: "requested_date",
    defaultDatePreset: "last30Days",
    defaultSort: {
      column: "recut_reason",
      direction: "asc",
    },
    defaultGrouping: ["recut_reason"],
    defaultAggregations: [
      agg("recut_id", "count", "Recut Count"),
      agg("pieces", "sum", "Total Pieces"),
      agg("hours_open", "avg", "Average Hours Open"),
    ],
    defaultVisualization: "bar",
    simpleFilters: [
      "recut_reason",
      "requested_department",
      "recut_status",
      "operator",
      "sales_order_display",
    ],
    summaryCards: [
      {
        key: "recuts",
        label: "Recuts",
        sourceColumn: "count_recut_id",
        function: "sum",
        format: "number",
      },
      {
        key: "pieces",
        label: "Pieces",
        sourceColumn: "sum_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "reasons",
        label: "Reasons",
        sourceColumn: "recut_reason",
        function: "countDistinct",
        format: "number",
      },
    ],
  },

  {
    key: "recutSummaryByRequestedDepartment",
    label: "Recut Summary by Requested Department",
    description:
      "Recut counts and pieces grouped by requested department. Good for department-level workload and trend review.",
    category: "recuts",
    datasetKey: "recutActivity",
    defaultColumns: [
      "requested_department",
      "recut_id",
      "pieces",
      "hours_open",
      "hours_to_complete",
    ],
    defaultDateColumn: "requested_date",
    defaultDatePreset: "last30Days",
    defaultSort: {
      column: "requested_department",
      direction: "asc",
    },
    defaultGrouping: ["requested_department"],
    defaultAggregations: [
      agg("recut_id", "count", "Recut Count"),
      agg("pieces", "sum", "Total Pieces"),
      agg("hours_open", "avg", "Average Hours Open"),
      agg("hours_to_complete", "avg", "Average Hours to Complete"),
    ],
    defaultVisualization: "bar",
    simpleFilters: [
      "requested_department",
      "recut_status",
      "operator",
      "recut_reason",
      "sales_order_display",
    ],
    summaryCards: [
      {
        key: "recuts",
        label: "Recuts",
        sourceColumn: "count_recut_id",
        function: "sum",
        format: "number",
      },
      {
        key: "pieces",
        label: "Pieces",
        sourceColumn: "sum_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "departments",
        label: "Departments",
        sourceColumn: "requested_department",
        function: "countDistinct",
        format: "number",
      },
    ],
  },

  {
    key: "openRecutsByStatus",
    label: "Open Recuts by Status",
    description:
      "Open recut workload grouped by recut status. Completed recuts are excluded by default.",
    category: "recuts",
    datasetKey: "recutActivity",
    defaultColumns: [
      "recut_status",
      "requested_date",
      "recut_id",
      "requested_department",
      "sales_order_display",
      "recut_reason",
      "pieces",
      "operator",
      "hours_open",
      "record_url",
    ],
    defaultDateColumn: "requested_date",
    defaultDatePreset: "last30Days",
    defaultSort: {
      column: "requested_date",
      direction: "asc",
    },
    defaultGrouping: ["recut_status"],
    defaultAggregations: [
      agg("recut_id", "count", "Recut Count"),
      agg("pieces", "sum", "Total Pieces"),
      agg("hours_open", "avg", "Average Hours Open"),
    ],
    defaultVisualization: "bar",
    defaultFilters: {
      is_completed: { operator: "isFalse" },
    },
    defaultFilterLogic: "AND",
    simpleFilters: [
      "recut_status",
      "requested_department",
      "operator",
      "recut_reason",
      "sales_order_display",
    ],
    summaryCards: [
      {
        key: "openRecuts",
        label: "Open Recuts",
        sourceColumn: "count_recut_id",
        function: "sum",
        format: "number",
      },
      {
        key: "pieces",
        label: "Pieces",
        sourceColumn: "sum_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "avgOpen",
        label: "Avg Hours Open",
        sourceColumn: "avg_hours_open",
        function: "avg",
        format: "hours",
      },
    ],
  },

  {
    key: "recutsBySalesOrder",
    label: "Recuts by Sales Order",
    description:
      "Recut counts and pieces grouped by sales order. Good for finding sales orders with repeat recut activity.",
    category: "recuts",
    datasetKey: "recutActivity",
    defaultColumns: [
      "sales_order_display",
      "recut_id",
      "requested_date",
      "requested_department",
      "recut_reason",
      "pieces",
      "operator",
      "recut_status",
      "record_url",
    ],
    defaultDateColumn: "requested_date",
    defaultDatePreset: "last30Days",
    defaultSort: {
      column: "sales_order_display",
      direction: "asc",
    },
    defaultGrouping: ["sales_order_display"],
    defaultAggregations: [
      agg("recut_id", "count", "Recut Count"),
      agg("pieces", "sum", "Total Pieces"),
    ],
    defaultVisualization: "bar",
    simpleFilters: [
      "sales_order_display",
      "sales_order_base",
      "requested_department",
      "recut_status",
      "operator",
      "recut_reason",
    ],
    summaryCards: [
      {
        key: "recuts",
        label: "Recuts",
        sourceColumn: "count_recut_id",
        function: "sum",
        format: "number",
      },
      {
        key: "pieces",
        label: "Pieces",
        sourceColumn: "sum_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "salesOrders",
        label: "Sales Orders",
        sourceColumn: "sales_order_display",
        function: "countDistinct",
        format: "number",
      },
    ],
  },

  {
    key: "recutsByCapStyle",
    label: "Recuts by Cap Style",
    description:
      "Recut counts and pieces grouped by cap style. Good for spotting style-related recut patterns.",
    category: "recuts",
    datasetKey: "recutActivity",
    defaultColumns: [
      "cap_style",
      "recut_id",
      "requested_date",
      "sales_order_display",
      "recut_reason",
      "pieces",
      "operator",
      "recut_status",
    ],
    defaultDateColumn: "requested_date",
    defaultDatePreset: "last30Days",
    defaultSort: {
      column: "cap_style",
      direction: "asc",
    },
    defaultGrouping: ["cap_style"],
    defaultAggregations: [
      agg("recut_id", "count", "Recut Count"),
      agg("pieces", "sum", "Total Pieces"),
    ],
    defaultVisualization: "bar",
    simpleFilters: [
      "cap_style",
      "recut_reason",
      "requested_department",
      "recut_status",
      "operator",
      "sales_order_display",
    ],
    summaryCards: [
      {
        key: "recuts",
        label: "Recuts",
        sourceColumn: "count_recut_id",
        function: "sum",
        format: "number",
      },
      {
        key: "pieces",
        label: "Pieces",
        sourceColumn: "sum_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "styles",
        label: "Styles",
        sourceColumn: "cap_style",
        function: "countDistinct",
        format: "number",
      },
    ],
  },

  {
    key: "completedRecutsByCompletionTime",
    label: "Completed Recuts by Completion Time",
    description:
      "Completed recuts grouped by department and reason, with average completion time.",
    category: "recuts",
    datasetKey: "recutActivity",
    defaultColumns: [
      "completed_at",
      "recut_id",
      "requested_department",
      "sales_order_display",
      "recut_reason",
      "pieces",
      "operator",
      "hours_to_complete",
      "record_url",
    ],
    defaultDateColumn: "completed_at",
    defaultDatePreset: "last30Days",
    defaultSort: {
      column: "completed_at",
      direction: "desc",
    },
    defaultGrouping: ["requested_department", "recut_reason"],
    defaultAggregations: [
      agg("recut_id", "count", "Completed Recut Count"),
      agg("pieces", "sum", "Completed Pieces"),
      agg("hours_to_complete", "avg", "Average Hours to Complete"),
    ],
    defaultVisualization: "bar",
    defaultFilters: {
      is_completed: { operator: "isTrue" },
    },
    defaultFilterLogic: "AND",
    simpleFilters: [
      "requested_department",
      "operator",
      "recut_reason",
      "sales_order_display",
      "completed_by",
    ],
    summaryCards: [
      {
        key: "completed",
        label: "Completed Recuts",
        sourceColumn: "count_recut_id",
        function: "sum",
        format: "number",
      },
      {
        key: "pieces",
        label: "Completed Pieces",
        sourceColumn: "sum_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "avgComplete",
        label: "Avg Hours to Complete",
        sourceColumn: "avg_hours_to_complete",
        function: "avg",
        format: "hours",
      },
    ],
  },

  {
    key: "warehousePrintedNotCompletedRecuts",
    label: "Warehouse Printed / Not Completed",
    description:
      "Recuts that have been printed for warehouse but are not completed. Do Not Pull records are excluded by default.",
    category: "recuts",
    datasetKey: "recutActivity",
    defaultColumns: [
      "warehouse_printed_at",
      "requested_date",
      "recut_id",
      "requested_department",
      "sales_order_display",
      "recut_reason",
      "pieces",
      "operator",
      "recut_status",
      "hours_open",
      "record_url",
    ],
    defaultDateColumn: "warehouse_printed_at",
    defaultDatePreset: "last30Days",
    defaultSort: {
      column: "warehouse_printed_at",
      direction: "asc",
    },
    defaultGrouping: ["requested_department", "recut_status"],
    defaultAggregations: [
      agg("recut_id", "count", "Printed Recut Count"),
      agg("pieces", "sum", "Printed Pieces"),
      agg("hours_open", "avg", "Average Hours Open"),
    ],
    defaultVisualization: "bar",
    defaultFilters: {
      warehouse_printed: { operator: "isTrue" },
      is_completed: { operator: "isFalse" },
      do_not_pull: { operator: "isFalse" },
    },
    defaultFilterLogic: "AND",
    simpleFilters: [
      "requested_department",
      "recut_status",
      "operator",
      "recut_reason",
      "sales_order_display",
      "warehouse_printed_by",
    ],
    summaryCards: [
      {
        key: "printedOpen",
        label: "Printed / Open",
        sourceColumn: "count_recut_id",
        function: "sum",
        format: "number",
      },
      {
        key: "pieces",
        label: "Pieces",
        sourceColumn: "sum_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "avgOpen",
        label: "Avg Hours Open",
        sourceColumn: "avg_hours_open",
        function: "avg",
        format: "hours",
      },
    ],
  },

  {
    key: "doNotPullRecuts",
    label: "Do Not Pull Recuts",
    description:
      "Recuts marked Do Not Pull. Good for reviewing warehouse exceptions and holds.",
    category: "recuts",
    datasetKey: "recutActivity",
    defaultColumns: [
      "do_not_pull_at",
      "requested_date",
      "recut_id",
      "requested_department",
      "sales_order_display",
      "recut_reason",
      "pieces",
      "operator",
      "recut_status",
      "record_url",
    ],
    defaultDateColumn: "do_not_pull_at",
    defaultDatePreset: "last30Days",
    defaultSort: {
      column: "do_not_pull_at",
      direction: "desc",
    },
    defaultGrouping: ["requested_department", "recut_status"],
    defaultAggregations: [
      agg("recut_id", "count", "Do Not Pull Count"),
      agg("pieces", "sum", "Do Not Pull Pieces"),
    ],
    defaultVisualization: "bar",
    defaultFilters: {
      do_not_pull: { operator: "isTrue" },
    },
    defaultFilterLogic: "AND",
    simpleFilters: [
      "requested_department",
      "recut_status",
      "operator",
      "recut_reason",
      "sales_order_display",
      "do_not_pull_by",
    ],
    summaryCards: [
      {
        key: "doNotPull",
        label: "Do Not Pull",
        sourceColumn: "count_recut_id",
        function: "sum",
        format: "number",
      },
      {
        key: "pieces",
        label: "Pieces",
        sourceColumn: "sum_pieces",
        function: "sum",
        format: "number",
      },
    ],
  },

  {
    key: "operatorRecutRateSummary",
    label: "Operator Recut Rate Summary",
    description:
      "Production cohort recut-rate summary by operator. Production is filtered by shift date, then matching recuts are attached by normalized operator and sales order base.",
    category: "recuts",
    datasetKey: "operatorRecutRate",
    defaultColumns: [
      "operator_name",
      "produced_pieces",
      "accountable_recut_pieces",
      "accountable_recut_count",
      "accountable_recut_piece_rate",
    ],
    defaultDateColumn: "production_shift_date",
    defaultDatePreset: "last7Days",
    defaultSort: {
      column: "accountable_recut_piece_rate",
      direction: "desc",
    },
    defaultGrouping: ["operator_name"],
    defaultAggregations: [
      agg("produced_pieces", "sum", "Produced Pieces"),
      agg("accountable_recut_pieces", "sum", "Accountable Recut Pieces"),
      agg("accountable_recut_count", "sum", "Accountable Recut Count"),
      agg("accountable_recut_piece_rate", "avg", "Average Accountable Recut Rate %"),
    ],
    defaultVisualization: "bar",
    simpleFilters: ["operator_name", "sales_order_base", "accountable_recut_piece_rate"],
    summaryCards: [
      {
        key: "producedPieces",
        label: "Produced Pieces",
        sourceColumn: "sum_produced_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "accountablePieces",
        label: "Accountable Recut Pieces",
        sourceColumn: "sum_accountable_recut_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "accountableRecuts",
        label: "Accountable Recuts",
        sourceColumn: "sum_accountable_recut_count",
        function: "sum",
        format: "number",
      },
      {
        key: "avgAccountableRate",
        label: "Avg Accountable Rate",
        sourceColumn: "avg_accountable_recut_piece_rate",
        function: "avg",
        format: "percent",
      },
    ],
  },

  {
    key: "operatorRecutRateBySalesOrder",
    label: "Operator Recut Rate by Sales Order",
    description:
      "Operator recut-rate detail by sales order base. This is the primary review grain for matching production to recuts.",
    category: "recuts",
    datasetKey: "operatorRecutRate",
    defaultColumns: [
      "operator_name",
      "sales_order_base",
      "production_first_shift_date",
      "production_last_shift_date",
      "produced_pieces",
      "gross_recut_pieces",
      "excluded_recut_pieces",
      "accountable_recut_pieces",
      "accountable_recut_piece_rate",
      "recut_reasons",
    ],
    defaultDateColumn: "production_shift_date",
    defaultDatePreset: "last7Days",
    defaultSort: {
      column: "accountable_recut_piece_rate",
      direction: "desc",
    },
    defaultGrouping: [],
    defaultAggregations: [],
    defaultVisualization: "datatable",
    simpleFilters: [
      "operator_name",
      "sales_order_base",
      "accountable_recut_piece_rate",
      "gross_recut_piece_rate",
      "recut_reasons",
    ],
    summaryCards: [
      {
        key: "rows",
        label: "Operator / SO Rows",
        function: "countRows",
        format: "number",
      },
      {
        key: "producedPieces",
        label: "Produced Pieces",
        sourceColumn: "produced_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "accountablePieces",
        label: "Accountable Recut Pieces",
        sourceColumn: "accountable_recut_pieces",
        function: "sum",
        format: "number",
      },
    ],
  },

  {
    key: "highAccountableRecutRateOperators",
    label: "High Accountable Recut Rate Operators",
    description:
      "Operators over the default accountable recut-rate threshold. The threshold is editable live in report filters.",
    category: "recuts",
    datasetKey: "operatorRecutRate",
    defaultColumns: [
      "operator_name",
      "produced_pieces",
      "accountable_recut_pieces",
      "accountable_recut_count",
      "accountable_recut_piece_rate",
    ],
    defaultDateColumn: "production_shift_date",
    defaultDatePreset: "last7Days",
    defaultSort: {
      column: "accountable_recut_piece_rate",
      direction: "desc",
    },
    defaultGrouping: ["operator_name"],
    defaultAggregations: [
      agg("produced_pieces", "sum", "Produced Pieces"),
      agg("accountable_recut_pieces", "sum", "Accountable Recut Pieces"),
      agg("accountable_recut_count", "sum", "Accountable Recut Count"),
      agg("accountable_recut_piece_rate", "avg", "Average Accountable Recut Rate %"),
    ],
    defaultVisualization: "bar",
    defaultFilters: {
      accountable_recut_piece_rate: { operator: "numberRange", from: 1 },
    },
    defaultFilterLogic: "AND",
    simpleFilters: ["operator_name", "accountable_recut_piece_rate"],
    summaryCards: [
      {
        key: "operators",
        label: "Operators Over Threshold",
        sourceColumn: "operator_name",
        function: "countDistinct",
        format: "number",
      },
      {
        key: "producedPieces",
        label: "Produced Pieces",
        sourceColumn: "sum_produced_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "accountablePieces",
        label: "Accountable Recut Pieces",
        sourceColumn: "sum_accountable_recut_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "avgAccountableRate",
        label: "Avg Accountable Rate",
        sourceColumn: "avg_accountable_recut_piece_rate",
        function: "avg",
        format: "percent",
      },
    ],
  },

  {
    key: "highAccountableRecutRateSalesOrders",
    label: "High Accountable Recut Rate Sales Orders",
    description:
      "Operator and sales order rows over the default accountable recut-rate threshold. The threshold is editable live in report filters.",
    category: "recuts",
    datasetKey: "operatorRecutRate",
    defaultColumns: [
      "operator_name",
      "sales_order_base",
      "production_first_shift_date",
      "production_last_shift_date",
      "produced_pieces",
      "accountable_recut_pieces",
      "accountable_recut_count",
      "accountable_recut_piece_rate",
      "recut_reasons",
    ],
    defaultDateColumn: "production_shift_date",
    defaultDatePreset: "last7Days",
    defaultSort: {
      column: "accountable_recut_piece_rate",
      direction: "desc",
    },
    defaultGrouping: [],
    defaultAggregations: [],
    defaultVisualization: "datatable",
    defaultFilters: {
      accountable_recut_piece_rate: { operator: "numberRange", from: 1 },
    },
    defaultFilterLogic: "AND",
    simpleFilters: [
      "operator_name",
      "sales_order_base",
      "accountable_recut_piece_rate",
      "recut_reasons",
    ],
    summaryCards: [
      {
        key: "rows",
        label: "Rows Over Threshold",
        function: "countRows",
        format: "number",
      },
      {
        key: "producedPieces",
        label: "Produced Pieces",
        sourceColumn: "produced_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "accountablePieces",
        label: "Accountable Recut Pieces",
        sourceColumn: "accountable_recut_pieces",
        function: "sum",
        format: "number",
      },
    ],
  },

  {
    key: "unclassifiedRecutReasons",
    label: "Unclassified Recut Reasons",
    description:
      "Recut reasons that do not yet have an active accountability rule. Use this to decide which reasons should be excluded from operator accountability.",
    category: "recuts",
    datasetKey: "unclassifiedRecutReasons",
    defaultColumns: [
      "recut_reason",
      "recut_reason_key",
      "recut_count",
      "recut_pieces",
      "first_requested_date",
      "last_requested_date",
    ],
    defaultDateColumn: "last_requested_date",
    defaultDatePreset: "last365Days",
    defaultSort: {
      column: "recut_count",
      direction: "desc",
    },
    defaultGrouping: [],
    defaultAggregations: [],
    defaultVisualization: "datatable",
    simpleFilters: ["recut_reason", "recut_reason_key"],
    summaryCards: [
      {
        key: "rows",
        label: "Unclassified Reasons",
        function: "countRows",
        format: "number",
      },
      {
        key: "recuts",
        label: "Recuts",
        sourceColumn: "recut_count",
        function: "sum",
        format: "number",
      },
      {
        key: "pieces",
        label: "Pieces",
        sourceColumn: "recut_pieces",
        function: "sum",
        format: "number",
      },
    ],
  },
];