// lib/reports/reportRegistry.ts

import type { ReportDataset, ReportRole } from "./reportTypes";

const reportAccessRoles: ReportRole[] = ["ADMIN", "MANAGER", "SUPERVISOR"];

export const reportDatasets: Record<string, ReportDataset> = {
  productionActivity: {
    key: "productionActivity",
    label: "Production Activity",
    description:
      "Cross-department production activity by shift date, department, operator, sales order, and production metrics.",
    sourceSql: "reporting.v_production_activity",
    category: "production",
    allowedRoles: reportAccessRoles,
    defaultColumns: [
      "shift_date",
      "source_module",
      "department",
      "shift",
      "operator_name",
      "sales_order_display",
      "detail_number",
      "metric_pieces",
      "metric_dozens",
    ],
    defaultSort: {
      column: "shift_date",
      direction: "desc",
    },
    columns: [
      {
        key: "shift_date",
        label: "Shift Date",
        sql: "shift_date",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "entry_ts",
        label: "Entry Timestamp",
        sql: "entry_ts",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
      {
        key: "source_module",
        label: "Module",
        sql: "source_module",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "department",
        label: "Department",
        sql: "department",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "shift",
        label: "Shift",
        sql: "shift",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "operator_name",
        label: "Operator",
        sql: "operator_name",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "employee_number",
        label: "Employee #",
        sql: "employee_number",
        type: "number",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "sales_order_display",
        label: "Sales Order",
        sql: "sales_order_display",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "sales_order_base",
        label: "Sales Order Base",
        sql: "sales_order_base",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "detail_number",
        label: "Detail",
        sql: "detail_number",
        type: "number",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "machine",
        label: "Machine",
        sql: "machine",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "location",
        label: "Location",
        sql: "location",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "metric_pieces",
        label: "Pieces",
        sql: "metric_pieces",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "metric_dozens",
        label: "Dozens",
        sql: "metric_dozens",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "metric_total_stitches",
        label: "Total Stitches",
        sql: "metric_total_stitches",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "metric_inspected",
        label: "Inspected",
        sql: "metric_inspected",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "metric_rejected",
        label: "Rejected",
        sql: "metric_rejected",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "metric_good",
        label: "Good",
        sql: "metric_good",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "record_url",
        label: "Open Record",
        sql: "record_url",
        type: "text",
      },
    ],
  },

  recutActivity: {
    key: "recutActivity",
    label: "Recut Activity",
    description:
      "Recut requests, approvals, warehouse status, completion status, and aging.",
    sourceSql: "reporting.v_recut_activity",
    category: "recuts",
    allowedRoles: reportAccessRoles,
    defaultColumns: [
      "requested_date",
      "recut_id",
      "requested_department",
      "sales_order_display",
      "detail_number",
      "recut_reason",
      "pieces",
      "recut_status",
    ],
    defaultSort: {
      column: "requested_date",
      direction: "desc",
    },
    columns: [
      {
        key: "record_id",
        label: "Record ID",
        sql: "record_id",
        type: "text",
        filterable: true,
        sortable: true,
      },
      {
        key: "requested_date",
        label: "Requested Date",
        sql: "requested_date",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "requested_at",
        label: "Requested At",
        sql: "requested_at",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
      {
        key: "recut_id",
        label: "Recut #",
        sql: "recut_id",
        type: "number",
        filterable: true,
        sortable: true,
        defaultVisible: true,
      },
      {
        key: "requested_department",
        label: "Requested Department",
        sql: "requested_department",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "requested_by_name",
        label: "Requested By",
        sql: "requested_by_name",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "requested_by_employee_number",
        label: "Requested By Employee #",
        sql: "requested_by_employee_number",
        type: "number",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "sales_order_display",
        label: "Sales Order",
        sql: "sales_order_display",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "sales_order_base",
        label: "Sales Order Base",
        sql: "sales_order_base",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "sales_order",
        label: "Sales Order Raw",
        sql: "sales_order",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "detail_number",
        label: "Detail",
        sql: "detail_number",
        type: "number",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "design_name",
        label: "Design",
        sql: "design_name",
        type: "text",
        filterable: true,
        sortable: true,
      },
      {
        key: "recut_reason",
        label: "Reason",
        sql: "recut_reason",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "cap_style",
        label: "Cap Style",
        sql: "cap_style",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "pieces",
        label: "Pieces",
        sql: "pieces",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "operator",
        label: "Operator",
        sql: "operator",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "deliver_to",
        label: "Deliver To",
        sql: "deliver_to",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "supervisor_approved",
        label: "Supervisor Approved",
        sql: "supervisor_approved",
        type: "boolean",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "supervisor_approved_at",
        label: "Supervisor Approved At",
        sql: "supervisor_approved_at",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
      {
        key: "supervisor_approved_by",
        label: "Supervisor Approved By",
        sql: "supervisor_approved_by",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "warehouse_printed",
        label: "Warehouse Printed",
        sql: "warehouse_printed",
        type: "boolean",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "warehouse_printed_at",
        label: "Warehouse Printed At",
        sql: "warehouse_printed_at",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
      {
        key: "warehouse_printed_by",
        label: "Warehouse Printed By",
        sql: "warehouse_printed_by",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "do_not_pull",
        label: "Do Not Pull",
        sql: "do_not_pull",
        type: "boolean",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "do_not_pull_at",
        label: "Do Not Pull At",
        sql: "do_not_pull_at",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
      {
        key: "do_not_pull_by",
        label: "Do Not Pull By",
        sql: "do_not_pull_by",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "is_completed",
        label: "Completed",
        sql: "is_completed",
        type: "boolean",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "completed_at",
        label: "Completed At",
        sql: "completed_at",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
      {
        key: "completed_by",
        label: "Completed By",
        sql: "completed_by",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "recut_status",
        label: "Status",
        sql: "recut_status",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "hours_to_complete",
        label: "Hours to Complete",
        sql: "hours_to_complete",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "hours_open",
        label: "Hours Open",
        sql: "hours_open",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "notes",
        label: "Notes",
        sql: "notes",
        type: "text",
        filterable: true,
      },
      {
        key: "created_at",
        label: "Created At",
        sql: "created_at",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
      {
        key: "updated_at",
        label: "Updated At",
        sql: "updated_at",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
      {
        key: "is_voided",
        label: "Voided",
        sql: "is_voided",
        type: "boolean",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "record_url",
        label: "Open Record",
        sql: "record_url",
        type: "text",
      },
    ],
  },

  operatorRecutRate: {
    key: "operatorRecutRate",
    label: "Operator Recut Rate",
    description:
      "Production cohort reporting that compares matched recut pieces against total produced pieces by normalized operator and sales order base.",
    sourceSql: "(SELECT 1 AS placeholder) operator_recut_rate_placeholder",
    category: "recuts",
    allowedRoles: reportAccessRoles,
    defaultColumns: [
      "operator_name",
      "sales_order_base",
      "production_first_shift_date",
      "production_last_shift_date",
      "produced_pieces",
      "production_entry_count",
      "gross_recut_pieces",
      "excluded_recut_pieces",
      "accountable_recut_pieces",
      "accountable_recut_piece_rate",
      "recut_reasons",
    ],
    defaultSort: {
      column: "accountable_recut_piece_rate",
      direction: "desc",
    },
    columns: [
      {
        key: "production_shift_date",
        label: "Production Shift Date",
        sql: "production_shift_date",
        type: "date",
        filterable: true,
        filterOnly: true,
      },
      {
        key: "source_module",
        label: "Production Module",
        sql: "source_module",
        type: "text",
        filterable: true,
        filterOnly: true,
      },
      {
        key: "department",
        label: "Production Department",
        sql: "department",
        type: "text",
        filterable: true,
        filterOnly: true,
      },
      {
        key: "shift",
        label: "Production Shift",
        sql: "shift",
        type: "text",
        filterable: true,
        filterOnly: true,
      },
      {
        key: "operator_name",
        label: "Operator",
        sql: "base.operator_name",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "operator_match_key",
        label: "Operator Match Key",
        sql: "base.operator_match_key",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "sales_order_base",
        label: "Sales Order Base",
        sql: "base.sales_order_base",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "production_first_shift_date",
        label: "First Production Shift Date",
        sql: "base.production_first_shift_date",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "production_last_shift_date",
        label: "Last Production Shift Date",
        sql: "base.production_last_shift_date",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "produced_pieces",
        label: "Produced Pieces",
        sql: "base.produced_pieces",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "production_entry_count",
        label: "Production Entry Count",
        sql: "base.production_entry_count",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "gross_recut_count",
        label: "Gross Recut Count",
        sql: "base.gross_recut_count",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "gross_recut_pieces",
        label: "Gross Recut Pieces",
        sql: "base.gross_recut_pieces",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "excluded_recut_count",
        label: "Excluded Recut Count",
        sql: "base.excluded_recut_count",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "excluded_recut_pieces",
        label: "Excluded Recut Pieces",
        sql: "base.excluded_recut_pieces",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "accountable_recut_count",
        label: "Accountable Recut Count",
        sql: "base.accountable_recut_count",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "accountable_recut_pieces",
        label: "Accountable Recut Pieces",
        sql: "base.accountable_recut_pieces",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "gross_recut_piece_rate",
        label: "Gross Recut Piece Rate %",
        sql: "base.gross_recut_piece_rate",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "accountable_recut_piece_rate",
        label: "Accountable Recut Piece Rate %",
        sql: "base.accountable_recut_piece_rate",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "gross_recuts_per_1000_pieces",
        label: "Gross Recuts per 1,000 Pieces",
        sql: "base.gross_recuts_per_1000_pieces",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "accountable_recuts_per_1000_pieces",
        label: "Accountable Recuts per 1,000 Pieces",
        sql: "base.accountable_recuts_per_1000_pieces",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "recut_reasons",
        label: "Recut Reasons",
        sql: "base.recut_reasons",
        type: "text",
        filterable: true,
        sortable: true,
        defaultVisible: true,
      },
      {
        key: "excluded_recut_reasons",
        label: "Excluded Recut Reasons",
        sql: "base.excluded_recut_reasons",
        type: "text",
        filterable: true,
        sortable: true,
      },
      {
        key: "first_recut_requested_date",
        label: "First Recut Requested Date",
        sql: "base.first_recut_requested_date",
        type: "date",
        filterable: true,
        sortable: true,
      },
      {
        key: "last_recut_requested_date",
        label: "Last Recut Requested Date",
        sql: "base.last_recut_requested_date",
        type: "date",
        filterable: true,
        sortable: true,
      },
    ],
  },

  unclassifiedRecutReasons: {
    key: "unclassifiedRecutReasons",
    label: "Unclassified Recut Reasons",
    description:
      "Recut reasons that have appeared in recut activity but do not yet have an active accountability rule.",
    sourceSql: "reporting.v_unclassified_recut_reasons",
    category: "recuts",
    allowedRoles: reportAccessRoles,
    defaultColumns: [
      "recut_reason",
      "recut_reason_key",
      "recut_count",
      "recut_pieces",
      "first_requested_date",
      "last_requested_date",
    ],
    defaultSort: {
      column: "recut_count",
      direction: "desc",
    },
    columns: [
      {
        key: "recut_reason",
        label: "Reason",
        sql: "recut_reason",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "recut_reason_key",
        label: "Reason Key",
        sql: "recut_reason_key",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "recut_count",
        label: "Recut Count",
        sql: "recut_count",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "recut_pieces",
        label: "Recut Pieces",
        sql: "recut_pieces",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "first_requested_date",
        label: "First Requested Date",
        sql: "first_requested_date",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "last_requested_date",
        label: "Last Requested Date",
        sql: "last_requested_date",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
    ],
  },

  qcRejectAnalysis: {
    key: "qcRejectAnalysis",
    label: "QC Reject Analysis",
    description:
      "QC and Knit QC inspection/reject reporting by shift date, department, operator, sales order, reject reason, and reject rate.",
    sourceSql: "reporting.v_qc_reject_analysis",
    category: "quality",
    allowedRoles: reportAccessRoles,
    defaultColumns: [
      "shift_date",
      "source_module",
      "department",
      "shift",
      "operator_name",
      "sales_order_display",
      "detail_number",
      "inspected_quantity",
      "rejected_quantity",
      "reject_rate",
      "reject_reason",
    ],
    defaultSort: {
      column: "shift_date",
      direction: "desc",
    },
    columns: [
      {
        key: "shift_date",
        label: "Shift Date",
        sql: "shift_date",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "entry_ts",
        label: "Entry Timestamp",
        sql: "entry_ts",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
      {
        key: "source_module",
        label: "Module",
        sql: "source_module",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "department",
        label: "Department",
        sql: "department",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "shift",
        label: "Shift",
        sql: "shift",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "operator_name",
        label: "Operator",
        sql: "operator_name",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "employee_number",
        label: "Employee #",
        sql: "employee_number",
        type: "number",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "sales_order_display",
        label: "Sales Order",
        sql: "sales_order_display",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "sales_order_base",
        label: "Sales Order Base",
        sql: "sales_order_base",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "detail_number",
        label: "Detail",
        sql: "detail_number",
        type: "number",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "quality_area",
        label: "Quality Area",
        sql: "quality_area",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "order_quantity",
        label: "Order Quantity",
        sql: "order_quantity",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "inspected_quantity",
        label: "Inspected Quantity",
        sql: "inspected_quantity",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "rejected_quantity",
        label: "Rejected Quantity",
        sql: "rejected_quantity",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "good_quantity",
        label: "Good Quantity",
        sql: "good_quantity",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "shipped_quantity",
        label: "Shipped Quantity",
        sql: "shipped_quantity",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "reject_rate",
        label: "Reject Rate",
        sql: "reject_rate",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "reject_reason",
        label: "Reject Reason",
        sql: "reject_reason",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "notes",
        label: "Notes",
        sql: "notes",
        type: "text",
        filterable: true,
      },
      {
        key: "record_url",
        label: "Open Record",
        sql: "record_url",
        type: "text",
      },
    ],
  },

  workflowActivity: {
    key: "workflowActivity",
    label: "Workflow Activity",
    description:
      "Design workflow reporting by request, sales order, customer, status, due date, assignment, rush flag, and aging.",
    sourceSql: "reporting.v_workflow_activity",
    category: "workflow",
    allowedRoles: reportAccessRoles,
    defaultColumns: [
      "activity_date",
      "request_number",
      "sales_order_display",
      "customer_name",
      "status_label",
      "due_date",
      "created_by_name",
      "digitizer_name",
      "designer_name",
      "rush",
      "days_open",
    ],
    defaultSort: {
      column: "activity_ts",
      direction: "desc",
    },
    columns: [
      {
        key: "activity_ts",
        label: "Activity Timestamp",
        sql: "activity_ts",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
      {
        key: "activity_date",
        label: "Activity Date",
        sql: "activity_date",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "shift_date",
        label: "Shift Date",
        sql: "shift_date",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "request_number",
        label: "Request #",
        sql: "request_number",
        type: "text",
        filterable: true,
        sortable: true,
        defaultVisible: true,
      },
      {
        key: "sales_order_display",
        label: "Sales Order",
        sql: "sales_order_display",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "sales_order_base",
        label: "Sales Order Base",
        sql: "sales_order_base",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "po_number",
        label: "PO Number",
        sql: "po_number",
        type: "text",
        filterable: true,
        sortable: true,
      },
      {
        key: "tape_name",
        label: "Tape Name",
        sql: "tape_name",
        type: "text",
        filterable: true,
        sortable: true,
      },
      {
        key: "due_date",
        label: "Due Date",
        sql: "due_date",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "customer_name",
        label: "Customer",
        sql: "customer_name",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "customer_code",
        label: "Customer Code",
        sql: "customer_code",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "bin_code",
        label: "Bin",
        sql: "bin_code",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "created_by_name",
        label: "Created By",
        sql: "created_by_name",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "digitizer_name",
        label: "Digitizer",
        sql: "digitizer_name",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "designer_name",
        label: "Designer",
        sql: "designer_name",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "status_code",
        label: "Status Code",
        sql: "status_code",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "status_label",
        label: "Status",
        sql: "status_label",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "last_status_changed_at",
        label: "Last Status Changed",
        sql: "last_status_changed_at",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
      {
        key: "last_status_changed_by_name",
        label: "Last Status Changed By",
        sql: "last_status_changed_by_name",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "rush",
        label: "Rush",
        sql: "rush",
        type: "boolean",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "style_code",
        label: "Style",
        sql: "style_code",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "sample_so_number",
        label: "Sample SO",
        sql: "sample_so_number",
        type: "text",
        filterable: true,
        sortable: true,
      },
      {
        key: "stitch_count",
        label: "Stitch Count",
        sql: "stitch_count",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "art_proof",
        label: "Art Proof",
        sql: "art_proof",
        type: "boolean",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "days_until_due",
        label: "Days Until Due",
        sql: "days_until_due",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "days_open",
        label: "Days Open",
        sql: "days_open",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "record_url",
        label: "Open Record",
        sql: "record_url",
        type: "text",
      },
    ],
  },

  inboundShipmentActivity: {
    key: "inboundShipmentActivity",
    label: "Inbound Shipment Activity",
    description:
      "Inbound shipment reporting by container, status, ETA, forwarder, shipment type, customer, PO, destination, and line quantities.",
    sourceSql: "reporting.v_inbound_shipment_activity",
    category: "logistics",
    allowedRoles: reportAccessRoles,
    defaultColumns: [
      "eta",
      "inbound_shipment_number",
      "status_label",
      "container_number",
      "forwarder",
      "shipment_type",
      "container_destination",
      "po_number",
      "customer_name",
      "quantity",
      "line_carton_count",
      "record_url",
    ],
    defaultSort: {
      column: "eta",
      direction: "asc",
    },
    columns: [
      {
        key: "inbound_shipment_number",
        label: "Inbound Shipment #",
        sql: "inbound_shipment_number",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "status_code",
        label: "Status Code",
        sql: "status_code",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "status_label",
        label: "Status",
        sql: "status_label",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "mbl_number",
        label: "MBL #",
        sql: "mbl_number",
        type: "text",
        filterable: true,
        sortable: true,
      },
      {
        key: "hbl_number",
        label: "HBL #",
        sql: "hbl_number",
        type: "text",
        filterable: true,
        sortable: true,
      },
      {
        key: "container_number",
        label: "Container #",
        sql: "container_number",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "seal_number",
        label: "Seal #",
        sql: "seal_number",
        type: "text",
        filterable: true,
        sortable: true,
      },
      {
        key: "port",
        label: "Port",
        sql: "port",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "carrier",
        label: "Carrier",
        sql: "carrier",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "forwarder",
        label: "Forwarder",
        sql: "forwarder",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "shipment_type",
        label: "Shipment Type",
        sql: "shipment_type",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "container_destination",
        label: "Container Destination",
        sql: "container_destination",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "etd",
        label: "ETD",
        sql: "etd",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "eta",
        label: "ETA",
        sql: "eta",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "days_until_eta",
        label: "Days Until ETA",
        sql: "days_until_eta",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "days_past_eta",
        label: "Days Past ETA",
        sql: "days_past_eta",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "carton_count",
        label: "Header Cartons",
        sql: "carton_count",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "tariff_percentage",
        label: "Tariff %",
        sql: "tariff_percentage",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "po_number",
        label: "PO #",
        sql: "po_number",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "customer_name",
        label: "Customer",
        sql: "customer_name",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "logo",
        label: "Logo",
        sql: "logo",
        type: "text",
        filterable: true,
        sortable: true,
      },
      {
        key: "tracking",
        label: "Tracking",
        sql: "tracking",
        type: "text",
        filterable: true,
        sortable: true,
      },
      {
        key: "line_destination",
        label: "Line Destination",
        sql: "line_destination",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "quantity",
        label: "Line Quantity",
        sql: "quantity",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "line_carton_count",
        label: "Line Cartons",
        sql: "line_carton_count",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "created_at",
        label: "Created At",
        sql: "created_at",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
      {
        key: "created_by",
        label: "Created By",
        sql: "created_by",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "updated_at",
        label: "Updated At",
        sql: "updated_at",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
      {
        key: "updated_by",
        label: "Updated By",
        sql: "updated_by",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "record_url",
        label: "Open Record",
        sql: "record_url",
        type: "text",
      },
    ],
  },

  maintenanceActivity: {
    key: "maintenanceActivity",
    label: "Maintenance Activity",
    description:
      "CMMS work order reporting by department, asset, priority, tech, common issue, status, downtime, and aging.",
    sourceSql: "reporting.v_maintenance_activity",
    category: "maintenance",
    allowedRoles: reportAccessRoles,
    defaultColumns: [
      "requested_date",
      "work_order_id",
      "department",
      "asset",
      "priority",
      "tech",
      "common_issue",
      "status",
      "hours_open",
    ],
    defaultSort: {
      column: "requested_at",
      direction: "desc",
    },
    columns: [
      {
        key: "requested_at",
        label: "Requested At",
        sql: "requested_at",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
      {
        key: "requested_date",
        label: "Requested Date",
        sql: "requested_date",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "shift_date",
        label: "Shift Date",
        sql: "shift_date",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "work_order_id",
        label: "WO #",
        sql: "work_order_id",
        type: "number",
        filterable: true,
        sortable: true,
        defaultVisible: true,
      },
      {
        key: "requested_by_name",
        label: "Requested By",
        sql: "requested_by_name",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "department",
        label: "Department",
        sql: "department",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "asset",
        label: "Asset",
        sql: "asset",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "priority",
        label: "Priority",
        sql: "priority",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "tech",
        label: "Tech",
        sql: "tech",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "common_issue",
        label: "Common Issue",
        sql: "common_issue",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "work_order_type",
        label: "Work Order Type",
        sql: "work_order_type",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "status",
        label: "Status",
        sql: "status",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "operator_initials",
        label: "Operator Initials",
        sql: "operator_initials",
        type: "text",
        filterable: true,
        sortable: true,
      },
      {
        key: "down_time_recorded",
        label: "Downtime Recorded",
        sql: "down_time_recorded",
        type: "text",
        filterable: true,
        sortable: true,
      },
      {
        key: "hours_to_last_update",
        label: "Hours to Last Update",
        sql: "hours_to_last_update",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "hours_open",
        label: "Hours Open",
        sql: "hours_open",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "issue_dialogue",
        label: "Issue",
        sql: "issue_dialogue",
        type: "text",
        filterable: true,
      },
      {
        key: "resolution",
        label: "Resolution",
        sql: "resolution",
        type: "text",
        filterable: true,
      },
      {
        key: "record_url",
        label: "Open Record",
        sql: "record_url",
        type: "text",
      },
    ],
  },

  salesOrderActivity: {
    key: "salesOrderActivity",
    label: "Sales Order Activity",
    description:
      "Cross-module sales order activity across production, QC, recuts, and workflow.",
    sourceSql: "reporting.v_sales_order_activity",
    category: "cross_module",
    allowedRoles: reportAccessRoles,
    defaultColumns: [
      "sales_order_display",
      "detail_number",
      "activity_date",
      "source_module",
      "activity_type",
      "department",
      "operator_name",
      "quantity",
      "status",
    ],
    defaultSort: {
      column: "activity_ts",
      direction: "desc",
    },
    columns: [
      {
        key: "sales_order_display",
        label: "Sales Order",
        sql: "sales_order_display",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "sales_order_base",
        label: "Sales Order Base",
        sql: "sales_order_base",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "detail_number",
        label: "Detail",
        sql: "detail_number",
        type: "number",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "activity_ts",
        label: "Activity Timestamp",
        sql: "activity_ts",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
      {
        key: "activity_date",
        label: "Activity Date",
        sql: "activity_date",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "shift_date",
        label: "Shift Date",
        sql: "shift_date",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "source_module",
        label: "Module",
        sql: "source_module",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "activity_type",
        label: "Activity Type",
        sql: "activity_type",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "department",
        label: "Department",
        sql: "department",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "operator_name",
        label: "Operator/User",
        sql: "operator_name",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "employee_number",
        label: "Employee #",
        sql: "employee_number",
        type: "number",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "quantity",
        label: "Quantity",
        sql: "quantity",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "total_stitches",
        label: "Total Stitches",
        sql: "total_stitches",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "status",
        label: "Status",
        sql: "status",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "notes",
        label: "Notes",
        sql: "notes",
        type: "text",
        filterable: true,
      },
      {
        key: "record_url",
        label: "Open Record",
        sql: "record_url",
        type: "text",
      },
    ],
  },

  machineUtilization: {
    key: "machineUtilization",
    label: "Machine / Area Utilization",
    description:
      "First-pass machine and work-area activity reporting using embroidery machine output and production work sessions.",
    sourceSql: "reporting.v_machine_utilization",
    category: "production",
    allowedRoles: reportAccessRoles,
    defaultColumns: [
      "shift_date",
      "source_module",
      "activity_type",
      "department",
      "machine_or_area",
      "operator_name",
      "total_pieces",
      "total_stitches",
      "session_minutes",
      "open_session_count",
    ],
    defaultSort: {
      column: "shift_date",
      direction: "desc",
    },
    columns: [
      {
        key: "shift_date",
        label: "Shift Date",
        sql: "shift_date",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "shift",
        label: "Shift",
        sql: "shift",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "source_module",
        label: "Module",
        sql: "source_module",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "activity_type",
        label: "Activity Type",
        sql: "activity_type",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "department",
        label: "Department",
        sql: "department",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "machine_or_area",
        label: "Machine / Area",
        sql: "machine_or_area",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "operator_name",
        label: "Operator",
        sql: "operator_name",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
        defaultVisible: true,
      },
      {
        key: "employee_number",
        label: "Employee #",
        sql: "employee_number",
        type: "number",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "entry_count",
        label: "Entry Count",
        sql: "entry_count",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "total_pieces",
        label: "Total Pieces",
        sql: "total_pieces",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "total_stitches",
        label: "Total Stitches",
        sql: "total_stitches",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "session_count",
        label: "Session Count",
        sql: "session_count",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
      },
      {
        key: "session_minutes",
        label: "Session Minutes",
        sql: "session_minutes",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "open_session_count",
        label: "Open Sessions",
        sql: "open_session_count",
        type: "number",
        filterable: true,
        sortable: true,
        aggregatable: true,
        defaultVisible: true,
      },
      {
        key: "first_activity_ts",
        label: "First Activity",
        sql: "first_activity_ts",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
      {
        key: "last_activity_ts",
        label: "Last Activity",
        sql: "last_activity_ts",
        type: "datetime",
        filterable: true,
        sortable: true,
      },
    ],
  },

  adminDataQuality: {
    key: "adminDataQuality",
    label: "Admin / Data Quality",
    description:
      "Data quality checks such as missing shift dates, missing employee numbers, missing sales order normalization, and other reporting exceptions.",
    sourceSql: "reporting.v_data_quality_issues",
    category: "admin",
    allowedRoles: ["ADMIN"],
    defaultColumns: [
      "issue_date",
      "source_module",
      "issue_type",
      "severity",
      "record_id",
      "issue_message",
    ],
    defaultSort: {
      column: "issue_date",
      direction: "desc",
    },
    columns: [
      {
        key: "issue_date",
        label: "Issue Date",
        sql: "issue_date",
        type: "date",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "source_module",
        label: "Module",
        sql: "source_module",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "issue_type",
        label: "Issue Type",
        sql: "issue_type",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "severity",
        label: "Severity",
        sql: "severity",
        type: "text",
        filterable: true,
        sortable: true,
        groupable: true,
      },
      {
        key: "record_id",
        label: "Record ID",
        sql: "record_id",
        type: "text",
        filterable: true,
        sortable: true,
      },
      {
        key: "issue_message",
        label: "Issue",
        sql: "issue_message",
        type: "text",
        filterable: true,
      },
      {
        key: "record_url",
        label: "Open Record",
        sql: "record_url",
        type: "text",
      },
    ],
  },
};

export function getReportDataset(datasetKey: string) {
  return reportDatasets[datasetKey] ?? null;
}

export function listReportDatasetsForRole(role: string) {
  const normalizedRole = String(role || "").trim().toUpperCase();

  return Object.values(reportDatasets).filter((dataset) =>
    dataset.allowedRoles.includes(normalizedRole as ReportRole)
  );
}