// lib/reports/reportTemplates.ts

import type {
  ReportAggregateFunction,
  ReportAggregation,
  ReportFilterLogic,
  ReportFilterValue,
  ReportSortConfig,
  ReportVisualization,
} from "./reportTypes";
import type { ReportDatePresetKey } from "./reportDatePresets";
import { RECUT_REPORT_TEMPLATES } from "./recutReportTemplates";

export type ReportSummaryCardConfig = {
  key: string;
  label: string;
  sourceColumn?: string;
  function: "sum" | "avg" | "countRows" | "countDistinct" | "min" | "max";
  format?: "number" | "percent" | "hours";
};

export type ReportTemplate = {
  key: string;
  label: string;
  description: string;
  category:
    | "production"
    | "quality"
    | "recuts"
    | "workflow"
    | "maintenance"
    | "sales_order"
    | "machine"
    | "logistics";

  datasetKey: string;

  defaultColumns: string[];
  defaultDateColumn: string;
  defaultDatePreset: ReportDatePresetKey;

  defaultSort: ReportSortConfig;
  defaultGrouping: string[];
  defaultAggregations: ReportAggregation[];
  defaultVisualization: ReportVisualization;

  defaultFilters?: Record<string, ReportFilterValue>;
  defaultFilterLogic?: ReportFilterLogic;

  simpleFilters: string[];
  summaryCards: ReportSummaryCardConfig[];
};

function agg(
  column: string,
  fn: ReportAggregateFunction,
  label?: string
): ReportAggregation {
  return {
    column,
    function: fn,
    label,
  };
}

export const REPORT_TEMPLATES: ReportTemplate[] = [
  {
    key: "dailyProductionSummary",
    label: "Daily Production Summary",
    description:
      "Production totals by shift date and department. Good for daily supervisor review.",
    category: "production",
    datasetKey: "productionActivity",
    defaultColumns: [
      "shift_date",
      "department",
      "shift",
      "metric_pieces",
      "metric_dozens",
      "metric_total_stitches",
    ],
    defaultDateColumn: "shift_date",
    defaultDatePreset: "last7Days",
    defaultSort: {
      column: "shift_date",
      direction: "desc",
    },
    defaultGrouping: ["shift_date", "department"],
    defaultAggregations: [
      agg("metric_pieces", "sum", "Total Pieces"),
      agg("metric_dozens", "sum", "Total Dozens"),
      agg("metric_total_stitches", "sum", "Total Stitches"),
    ],
    defaultVisualization: "bar",
    simpleFilters: ["department", "shift", "operator_name", "sales_order_display"],
    summaryCards: [
      {
        key: "totalPieces",
        label: "Total Pieces",
        sourceColumn: "sum_metric_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "totalDozens",
        label: "Total Dozens",
        sourceColumn: "sum_metric_dozens",
        function: "sum",
        format: "number",
      },
      {
        key: "totalStitches",
        label: "Total Stitches",
        sourceColumn: "sum_metric_total_stitches",
        function: "sum",
        format: "number",
      },
      {
        key: "rows",
        label: "Rows",
        function: "countRows",
        format: "number",
      },
    ],
  },

  {
    key: "operatorProduction",
    label: "Operator Production",
    description:
      "Production totals by operator. Good for supervisor review and coaching conversations.",
    category: "production",
    datasetKey: "productionActivity",
    defaultColumns: [
      "department",
      "shift",
      "operator_name",
      "metric_pieces",
      "metric_dozens",
      "metric_total_stitches",
    ],
    defaultDateColumn: "shift_date",
    defaultDatePreset: "last7Days",
    defaultSort: {
      column: "operator_name",
      direction: "asc",
    },
    defaultGrouping: ["department", "shift", "operator_name"],
    defaultAggregations: [
      agg("metric_pieces", "sum", "Total Pieces"),
      agg("metric_dozens", "sum", "Total Dozens"),
      agg("metric_total_stitches", "sum", "Total Stitches"),
    ],
    defaultVisualization: "bar",
    simpleFilters: ["department", "shift", "operator_name", "sales_order_display"],
    summaryCards: [
      {
        key: "totalPieces",
        label: "Total Pieces",
        sourceColumn: "sum_metric_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "totalDozens",
        label: "Total Dozens",
        sourceColumn: "sum_metric_dozens",
        function: "sum",
        format: "number",
      },
      {
        key: "operators",
        label: "Operators",
        sourceColumn: "operator_name",
        function: "countDistinct",
        format: "number",
      },
    ],
  },

  {
    key: "departmentProduction",
    label: "Department Production",
    description:
      "Production totals by department and shift. Good for cross-department production review.",
    category: "production",
    datasetKey: "productionActivity",
    defaultColumns: ["department", "shift", "metric_pieces", "metric_dozens"],
    defaultDateColumn: "shift_date",
    defaultDatePreset: "last7Days",
    defaultSort: {
      column: "department",
      direction: "asc",
    },
    defaultGrouping: ["department", "shift"],
    defaultAggregations: [
      agg("metric_pieces", "sum", "Total Pieces"),
      agg("metric_dozens", "sum", "Total Dozens"),
      agg("metric_total_stitches", "sum", "Total Stitches"),
    ],
    defaultVisualization: "bar",
    simpleFilters: ["department", "shift"],
    summaryCards: [
      {
        key: "totalPieces",
        label: "Total Pieces",
        sourceColumn: "sum_metric_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "totalDozens",
        label: "Total Dozens",
        sourceColumn: "sum_metric_dozens",
        function: "sum",
        format: "number",
      },
      {
        key: "departments",
        label: "Departments",
        sourceColumn: "department",
        function: "countDistinct",
        format: "number",
      },
    ],
  },

    {
    key: "workSessionSummary",
    label: "Work Session Summary",
    description:
      "Work session totals by work date, module, and area. Good for reviewing session time and related production activity.",
    category: "production",
    datasetKey: "workSessionActivity",
    defaultColumns: [
      "work_date",
      "module_key",
      "area_label",
      "duration_hours",
      "submission_count",
      "total_quantity",
    ],
    defaultDateColumn: "work_date",
    defaultDatePreset: "last7Days",
    defaultSort: {
      column: "work_date",
      direction: "desc",
    },
    defaultGrouping: ["work_date", "module_key", "area_label"],
    defaultAggregations: [
      agg("id", "count", "Sessions"),
      agg("duration_hours", "sum", "Total Duration"),
      agg("submission_count", "sum", "Submissions"),
      agg("total_quantity", "sum", "Total Quantity"),
    ],
    defaultVisualization: "bar",
    simpleFilters: [
      "work_date",
      "module_key",
      "area_label",
      "operator_name",
      "employee_number",
      "shift",
      "is_open",
    ],
    summaryCards: [
      {
        key: "sessions",
        label: "Sessions",
        sourceColumn: "count_id",
        function: "sum",
        format: "number",
      },
      {
        key: "duration",
        label: "Total Duration",
        sourceColumn: "sum_duration_hours",
        function: "sum",
        format: "hours",
      },
      {
        key: "submissions",
        label: "Submissions",
        sourceColumn: "sum_submission_count",
        function: "sum",
        format: "number",
      },
      {
        key: "quantity",
        label: "Total Quantity",
        sourceColumn: "sum_total_quantity",
        function: "sum",
        format: "number",
      },
    ],
  },

  {
    key: "openWorkSessions",
    label: "Open Work Sessions",
    description:
      "Currently open work sessions with query-time duration and related submission counts.",
    category: "production",
    datasetKey: "workSessionActivity",
    defaultColumns: [
      "work_date",
      "time_in",
      "operator_name",
      "module_key",
      "area_label",
      "shift",
      "duration_hours",
      "submission_count",
      "total_quantity",
      "record_url",
    ],
    defaultDateColumn: "work_date",
    defaultDatePreset: "last7Days",
    defaultSort: {
      column: "time_in",
      direction: "desc",
    },
    defaultGrouping: [],
    defaultAggregations: [],
    defaultVisualization: "datatable",
    defaultFilters: {
      is_open: { operator: "isTrue" },
    },
    defaultFilterLogic: "AND",
    simpleFilters: [
      "operator_name",
      "employee_number",
      "module_key",
      "area_label",
      "shift",
      "work_date",
    ],
    summaryCards: [
      {
        key: "sessions",
        label: "Open Sessions",
        function: "countRows",
        format: "number",
      },
      {
        key: "duration",
        label: "Total Duration",
        sourceColumn: "duration_hours",
        function: "sum",
        format: "hours",
      },
      {
        key: "submissions",
        label: "Submissions",
        sourceColumn: "submission_count",
        function: "sum",
        format: "number",
      },
      {
        key: "quantity",
        label: "Total Quantity",
        sourceColumn: "total_quantity",
        function: "sum",
        format: "number",
      },
    ],
  },

  {
    key: "operatorWorkSessionSummary",
    label: "Operator Work Session Summary",
    description:
      "Work session totals grouped by operator and employee number.",
    category: "production",
    datasetKey: "workSessionActivity",
    defaultColumns: [
      "operator_name",
      "employee_number",
      "duration_hours",
      "submission_count",
      "total_quantity",
    ],
    defaultDateColumn: "work_date",
    defaultDatePreset: "last7Days",
    defaultSort: {
      column: "operator_name",
      direction: "asc",
    },
    defaultGrouping: ["operator_name", "employee_number"],
    defaultAggregations: [
      agg("id", "count", "Sessions"),
      agg("duration_hours", "sum", "Total Duration"),
      agg("submission_count", "sum", "Submissions"),
      agg("total_quantity", "sum", "Total Quantity"),
    ],
    defaultVisualization: "bar",
    simpleFilters: [
      "operator_name",
      "employee_number",
      "module_key",
      "area_label",
      "shift",
      "is_open",
    ],
    summaryCards: [
      {
        key: "sessions",
        label: "Sessions",
        sourceColumn: "count_id",
        function: "sum",
        format: "number",
      },
      {
        key: "duration",
        label: "Total Duration",
        sourceColumn: "sum_duration_hours",
        function: "sum",
        format: "hours",
      },
      {
        key: "submissions",
        label: "Submissions",
        sourceColumn: "sum_submission_count",
        function: "sum",
        format: "number",
      },
      {
        key: "quantity",
        label: "Total Quantity",
        sourceColumn: "sum_total_quantity",
        function: "sum",
        format: "number",
      },
    ],
  },

  {
    key: "areaWorkSessionSummary",
    label: "Area Work Session Summary",
    description:
      "Work session totals grouped by module, area, and shift.",
    category: "production",
    datasetKey: "workSessionActivity",
    defaultColumns: [
      "module_key",
      "area_label",
      "shift",
      "duration_hours",
      "submission_count",
      "total_quantity",
    ],
    defaultDateColumn: "work_date",
    defaultDatePreset: "last7Days",
    defaultSort: {
      column: "module_key",
      direction: "asc",
    },
    defaultGrouping: ["module_key", "area_label", "shift"],
    defaultAggregations: [
      agg("id", "count", "Sessions"),
      agg("duration_hours", "sum", "Total Duration"),
      agg("submission_count", "sum", "Submissions"),
      agg("total_quantity", "sum", "Total Quantity"),
    ],
    defaultVisualization: "bar",
    simpleFilters: [
      "module_key",
      "area_label",
      "shift",
      "operator_name",
      "employee_number",
      "is_open",
    ],
    summaryCards: [
      {
        key: "sessions",
        label: "Sessions",
        sourceColumn: "count_id",
        function: "sum",
        format: "number",
      },
      {
        key: "duration",
        label: "Total Duration",
        sourceColumn: "sum_duration_hours",
        function: "sum",
        format: "hours",
      },
      {
        key: "submissions",
        label: "Submissions",
        sourceColumn: "sum_submission_count",
        function: "sum",
        format: "number",
      },
      {
        key: "quantity",
        label: "Total Quantity",
        sourceColumn: "sum_total_quantity",
        function: "sum",
        format: "number",
      },
    ],
  },

  {
    key: "qcRejectSummary",
    label: "QC Reject Summary",
    description:
      "Inspection and reject totals by QC area, department, and reject reason.",
    category: "quality",
    datasetKey: "qcRejectAnalysis",
    defaultColumns: [
      "shift_date",
      "source_module",
      "department",
      "operator_name",
      "inspected_quantity",
      "rejected_quantity",
      "reject_rate",
      "reject_reason",
    ],
    defaultDateColumn: "shift_date",
    defaultDatePreset: "last30Days",
    defaultSort: {
      column: "shift_date",
      direction: "desc",
    },
    defaultGrouping: ["source_module", "department", "reject_reason"],
    defaultAggregations: [
      agg("inspected_quantity", "sum", "Total Inspected"),
      agg("rejected_quantity", "sum", "Total Rejected"),
      agg("good_quantity", "sum", "Good Quantity"),
      agg("reject_rate", "avg", "Average Reject Rate"),
    ],
    defaultVisualization: "bar",
    simpleFilters: [
      "source_module",
      "department",
      "shift",
      "operator_name",
      "sales_order_display",
      "reject_reason",
    ],
    summaryCards: [
      {
        key: "inspected",
        label: "Inspected",
        sourceColumn: "sum_inspected_quantity",
        function: "sum",
        format: "number",
      },
      {
        key: "rejected",
        label: "Rejected",
        sourceColumn: "sum_rejected_quantity",
        function: "sum",
        format: "number",
      },
      {
        key: "good",
        label: "Good Qty",
        sourceColumn: "sum_good_quantity",
        function: "sum",
        format: "number",
      },
      {
        key: "rejectRate",
        label: "Avg Reject Rate",
        sourceColumn: "avg_reject_rate",
        function: "avg",
        format: "percent",
      },
    ],
  },

  {
    key: "recutAging",
    label: "Recut Aging",
    description:
      "Recut request aging by department and status. Good for open workload review.",
    category: "recuts",
    datasetKey: "recutActivity",
    defaultColumns: [
      "requested_date",
      "recut_id",
      "requested_department",
      "sales_order_display",
      "recut_reason",
      "pieces",
      "recut_status",
      "hours_open",
      "record_url",
    ],
    defaultDateColumn: "requested_date",
    defaultDatePreset: "last30Days",
    defaultSort: {
      column: "requested_date",
      direction: "desc",
    },
    defaultGrouping: ["requested_department", "recut_status"],
    defaultAggregations: [
      agg("recut_id", "count", "Recut Count"),
      agg("pieces", "sum", "Total Pieces"),
      agg("hours_open", "avg", "Average Hours Open"),
    ],
    defaultVisualization: "bar",
    simpleFilters: [
      "requested_department",
      "recut_status",
      "operator",
      "sales_order_display",
      "recut_reason",
    ],
    summaryCards: [
      {
        key: "recuts",
        label: "Recuts",
        sourceColumn: "count_recut_id",
        function: "sum",
        format: "number",
      },
      {
        key: "pieces",
        label: "Pieces",
        sourceColumn: "sum_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "avgOpen",
        label: "Avg Hours Open",
        sourceColumn: "avg_hours_open",
        function: "avg",
        format: "hours",
      },
    ],
  },

  {
    key: "salesOrderActivity",
    label: "Sales Order Activity",
    description:
      "Cross-module activity for sales orders across production, QC, workflow, and recuts.",
    category: "sales_order",
    datasetKey: "salesOrderActivity",
    defaultColumns: [
      "sales_order_display",
      "detail_number",
      "activity_date",
      "source_module",
      "activity_type",
      "department",
      "operator_name",
      "quantity",
      "status",
      "record_url",
    ],
    defaultDateColumn: "activity_date",
    defaultDatePreset: "last30Days",
    defaultSort: {
      column: "activity_ts",
      direction: "desc",
    },
    defaultGrouping: [],
    defaultAggregations: [],
    defaultVisualization: "datatable",
    simpleFilters: [
      "sales_order_display",
      "source_module",
      "activity_type",
      "department",
      "operator_name",
      "status",
    ],
    summaryCards: [
      {
        key: "activityRows",
        label: "Activity Rows",
        function: "countRows",
        format: "number",
      },
      {
        key: "salesOrders",
        label: "Sales Orders",
        sourceColumn: "sales_order_display",
        function: "countDistinct",
        format: "number",
      },
      {
        key: "quantity",
        label: "Quantity",
        sourceColumn: "quantity",
        function: "sum",
        format: "number",
      },
    ],
  },

  {
    key: "workflowAging",
    label: "Workflow Aging",
    description:
      "Workflow request aging by status, due date, customer, designer, and digitizer.",
    category: "workflow",
    datasetKey: "workflowActivity",
    defaultColumns: [
      "activity_date",
      "request_number",
      "sales_order_display",
      "customer_name",
      "status_label",
      "due_date",
      "created_by_name",
      "digitizer_name",
      "designer_name",
      "rush",
      "days_open",
      "record_url",
    ],
    defaultDateColumn: "activity_date",
    defaultDatePreset: "last30Days",
    defaultSort: {
      column: "activity_ts",
      direction: "desc",
    },
    defaultGrouping: ["status_label"],
    defaultAggregations: [
      agg("request_number", "count", "Request Count"),
      agg("days_open", "avg", "Average Days Open"),
    ],
    defaultVisualization: "bar",
    simpleFilters: [
      "status_label",
      "customer_name",
      "sales_order_display",
      "created_by_name",
      "digitizer_name",
      "designer_name",
    ],
    summaryCards: [
      {
        key: "requests",
        label: "Requests",
        sourceColumn: "count_request_number",
        function: "sum",
        format: "number",
      },
      {
        key: "avgOpen",
        label: "Avg Days Open",
        sourceColumn: "avg_days_open",
        function: "avg",
        format: "number",
      },
      {
        key: "statuses",
        label: "Statuses",
        sourceColumn: "status_label",
        function: "countDistinct",
        format: "number",
      },
    ],
  },

  {
    key: "workflowByStatus",
    label: "Open Workflow by Status",
    description: "Workflow workload grouped by current status for manager review.",
    category: "workflow",
    datasetKey: "workflowActivity",
    defaultColumns: [
      "status_label",
      "request_number",
      "sales_order_display",
      "customer_name",
      "due_date",
      "days_open",
      "record_url",
    ],
    defaultDateColumn: "activity_date",
    defaultDatePreset: "last30Days",
    defaultSort: { column: "status_label", direction: "asc" },
    defaultGrouping: ["status_label"],
    defaultAggregations: [
      agg("request_number", "count", "Request Count"),
      agg("days_open", "avg", "Average Days Open"),
    ],
    defaultVisualization: "bar",
    defaultFilters: {
      status_code: { operator: "notIn", values: ["D", "E"] },
    },
    defaultFilterLogic: "AND",
    simpleFilters: [
      "status_label",
      "customer_name",
      "sales_order_display",
      "created_by_name",
      "digitizer_name",
      "designer_name",
    ],
    summaryCards: [
      {
        key: "requests",
        label: "Requests",
        sourceColumn: "count_request_number",
        function: "sum",
        format: "number",
      },
      {
        key: "avgOpen",
        label: "Avg Days Open",
        sourceColumn: "avg_days_open",
        function: "avg",
        format: "number",
      },
    ],
  },

  {
    key: "workflowOverdueRequests",
    label: "Overdue Workflow Requests",
    description: "Workflow requests with a due date before today.",
    category: "workflow",
    datasetKey: "workflowActivity",
    defaultColumns: [
      "due_date",
      "request_number",
      "sales_order_display",
      "customer_name",
      "status_label",
      "digitizer_name",
      "designer_name",
      "days_until_due",
      "record_url",
    ],
    defaultDateColumn: "due_date",
    defaultDatePreset: "last30Days",
    defaultSort: { column: "due_date", direction: "asc" },
    defaultGrouping: ["status_label"],
    defaultAggregations: [
      agg("request_number", "count", "Request Count"),
      agg("days_open", "avg", "Average Days Open"),
    ],
    defaultVisualization: "bar",
    defaultFilters: {
      days_until_due: { operator: "numberRange", to: -1 },
    },
    defaultFilterLogic: "AND",
    simpleFilters: [
      "status_label",
      "customer_name",
      "sales_order_display",
      "digitizer_name",
      "designer_name",
      "created_by_name",
    ],
    summaryCards: [
      {
        key: "requests",
        label: "Overdue Requests",
        sourceColumn: "count_request_number",
        function: "sum",
        format: "number",
      },
      {
        key: "avgOpen",
        label: "Avg Days Open",
        sourceColumn: "avg_days_open",
        function: "avg",
        format: "number",
      },
    ],
  },

  {
    key: "workflowDueTodayTomorrow",
    label: "Due Today / Due Tomorrow",
    description:
      "Workflow requests due today. Change the date filter to Tomorrow when needed.",
    category: "workflow",
    datasetKey: "workflowActivity",
    defaultColumns: [
      "due_date",
      "request_number",
      "sales_order_display",
      "customer_name",
      "status_label",
      "digitizer_name",
      "designer_name",
      "rush",
      "record_url",
    ],
    defaultDateColumn: "due_date",
    defaultDatePreset: "today",
    defaultSort: { column: "due_date", direction: "asc" },
    defaultGrouping: ["due_date", "status_label"],
    defaultAggregations: [agg("request_number", "count", "Request Count")],
    defaultVisualization: "bar",
    simpleFilters: [
      "status_label",
      "customer_name",
      "sales_order_display",
      "digitizer_name",
      "designer_name",
      "rush",
    ],
    summaryCards: [
      {
        key: "requests",
        label: "Requests",
        sourceColumn: "count_request_number",
        function: "sum",
        format: "number",
      },
      {
        key: "statuses",
        label: "Statuses",
        sourceColumn: "status_label",
        function: "countDistinct",
        format: "number",
      },
    ],
  },

  {
    key: "workflowRushRequests",
    label: "Rush Workflow Requests",
    description: "Rush workflow requests by due date, status, and assignment.",
    category: "workflow",
    datasetKey: "workflowActivity",
    defaultColumns: [
      "due_date",
      "request_number",
      "sales_order_display",
      "customer_name",
      "status_label",
      "digitizer_name",
      "designer_name",
      "rush",
      "record_url",
    ],
    defaultDateColumn: "activity_date",
    defaultDatePreset: "last30Days",
    defaultSort: { column: "due_date", direction: "asc" },
    defaultGrouping: ["status_label", "digitizer_name", "designer_name"],
    defaultAggregations: [agg("request_number", "count", "Request Count")],
    defaultVisualization: "bar",
    defaultFilters: {
      rush: { operator: "isTrue" },
    },
    defaultFilterLogic: "AND",
    simpleFilters: [
      "status_label",
      "customer_name",
      "sales_order_display",
      "digitizer_name",
      "designer_name",
      "created_by_name",
    ],
    summaryCards: [
      {
        key: "requests",
        label: "Rush Requests",
        sourceColumn: "count_request_number",
        function: "sum",
        format: "number",
      },
    ],
  },

  {
    key: "workflowByDigitizer",
    label: "Workflow by Digitizer",
    description: "Workflow request counts and aging by digitizer.",
    category: "workflow",
    datasetKey: "workflowActivity",
    defaultColumns: ["digitizer_name", "status_label", "request_number", "days_open"],
    defaultDateColumn: "activity_date",
    defaultDatePreset: "last30Days",
    defaultSort: { column: "digitizer_name", direction: "asc" },
    defaultGrouping: ["digitizer_name", "status_label"],
    defaultAggregations: [
      agg("request_number", "count", "Request Count"),
      agg("days_open", "avg", "Average Days Open"),
    ],
    defaultVisualization: "bar",
    simpleFilters: [
      "digitizer_name",
      "status_label",
      "customer_name",
      "sales_order_display",
    ],
    summaryCards: [
      {
        key: "requests",
        label: "Requests",
        sourceColumn: "count_request_number",
        function: "sum",
        format: "number",
      },
      {
        key: "digitizers",
        label: "Digitizers",
        sourceColumn: "digitizer_name",
        function: "countDistinct",
        format: "number",
      },
    ],
  },

  {
    key: "workflowByDesigner",
    label: "Workflow by Designer",
    description: "Workflow request counts and aging by designer.",
    category: "workflow",
    datasetKey: "workflowActivity",
    defaultColumns: ["designer_name", "status_label", "request_number", "days_open"],
    defaultDateColumn: "activity_date",
    defaultDatePreset: "last30Days",
    defaultSort: { column: "designer_name", direction: "asc" },
    defaultGrouping: ["designer_name", "status_label"],
    defaultAggregations: [
      agg("request_number", "count", "Request Count"),
      agg("days_open", "avg", "Average Days Open"),
    ],
    defaultVisualization: "bar",
    simpleFilters: [
      "designer_name",
      "status_label",
      "customer_name",
      "sales_order_display",
    ],
    summaryCards: [
      {
        key: "requests",
        label: "Requests",
        sourceColumn: "count_request_number",
        function: "sum",
        format: "number",
      },
      {
        key: "designers",
        label: "Designers",
        sourceColumn: "designer_name",
        function: "countDistinct",
        format: "number",
      },
    ],
  },

  {
    key: "workflowCreatedByCsRep",
    label: "Workflow Created by CS Rep",
    description: "Workflow requests by creator / CS rep.",
    category: "workflow",
    datasetKey: "workflowActivity",
    defaultColumns: [
      "created_by_name",
      "status_label",
      "request_number",
      "sales_order_display",
      "customer_name",
      "days_open",
    ],
    defaultDateColumn: "activity_date",
    defaultDatePreset: "last30Days",
    defaultSort: { column: "created_by_name", direction: "asc" },
    defaultGrouping: ["created_by_name", "status_label"],
    defaultAggregations: [agg("request_number", "count", "Request Count")],
    defaultVisualization: "bar",
    simpleFilters: [
      "created_by_name",
      "status_label",
      "customer_name",
      "sales_order_display",
    ],
    summaryCards: [
      {
        key: "requests",
        label: "Requests",
        sourceColumn: "count_request_number",
        function: "sum",
        format: "number",
      },
      {
        key: "creators",
        label: "Creators",
        sourceColumn: "created_by_name",
        function: "countDistinct",
        format: "number",
      },
    ],
  },

  {
    key: "workflowStatusChangeActivity",
    label: "Workflow Status Change Activity",
    description: "Workflow activity by last status change user and status.",
    category: "workflow",
    datasetKey: "workflowActivity",
    defaultColumns: [
      "last_status_changed_at",
      "request_number",
      "sales_order_display",
      "status_label",
      "last_status_changed_by_name",
      "record_url",
    ],
    defaultDateColumn: "last_status_changed_at",
    defaultDatePreset: "last30Days",
    defaultSort: { column: "last_status_changed_at", direction: "desc" },
    defaultGrouping: ["status_label", "last_status_changed_by_name"],
    defaultAggregations: [agg("request_number", "count", "Request Count")],
    defaultVisualization: "bar",
    simpleFilters: [
      "status_label",
      "last_status_changed_by_name",
      "customer_name",
      "sales_order_display",
      "created_by_name",
    ],
    summaryCards: [
      {
        key: "requests",
        label: "Status Changes",
        sourceColumn: "count_request_number",
        function: "sum",
        format: "number",
      },
      {
        key: "users",
        label: "Users",
        sourceColumn: "last_status_changed_by_name",
        function: "countDistinct",
        format: "number",
      },
    ],
  },

  {
    key: "workflowByCustomerSalesOrder",
    label: "Workflow by Customer / Sales Order",
    description: "Workflow request detail by customer and sales order.",
    category: "workflow",
    datasetKey: "workflowActivity",
    defaultColumns: [
      "customer_name",
      "sales_order_display",
      "request_number",
      "status_label",
      "due_date",
      "created_by_name",
      "digitizer_name",
      "designer_name",
      "record_url",
    ],
    defaultDateColumn: "activity_date",
    defaultDatePreset: "last30Days",
    defaultSort: { column: "customer_name", direction: "asc" },
    defaultGrouping: [],
    defaultAggregations: [],
    defaultVisualization: "datatable",
    simpleFilters: [
      "customer_name",
      "sales_order_display",
      "status_label",
      "created_by_name",
      "digitizer_name",
      "designer_name",
      "rush",
    ],
    summaryCards: [
      {
        key: "rows",
        label: "Requests",
        function: "countRows",
        format: "number",
      },
      {
        key: "customers",
        label: "Customers",
        sourceColumn: "customer_name",
        function: "countDistinct",
        format: "number",
      },
      {
        key: "salesOrders",
        label: "Sales Orders",
        sourceColumn: "sales_order_display",
        function: "countDistinct",
        format: "number",
      },
    ],
  },

  {
    key: "maintenanceActivity",
    label: "Maintenance Activity",
    description:
      "Maintenance work orders by department, asset, priority, tech, status, and aging.",
    category: "maintenance",
    datasetKey: "maintenanceActivity",
    defaultColumns: [
      "requested_date",
      "work_order_id",
      "department",
      "asset",
      "priority",
      "tech",
      "common_issue",
      "status",
      "hours_open",
      "record_url",
    ],
    defaultDateColumn: "requested_date",
    defaultDatePreset: "last30Days",
    defaultSort: {
      column: "requested_at",
      direction: "desc",
    },
    defaultGrouping: ["status", "priority", "department"],
    defaultAggregations: [
      agg("work_order_id", "count", "Work Order Count"),
      agg("hours_open", "avg", "Average Hours Open"),
    ],
    defaultVisualization: "bar",
    simpleFilters: ["department", "asset", "priority", "tech", "status", "common_issue"],
    summaryCards: [
      {
        key: "workOrders",
        label: "Work Orders",
        sourceColumn: "count_work_order_id",
        function: "sum",
        format: "number",
      },
      {
        key: "avgOpen",
        label: "Avg Hours Open",
        sourceColumn: "avg_hours_open",
        function: "avg",
        format: "hours",
      },
      {
        key: "statuses",
        label: "Statuses",
        sourceColumn: "status",
        function: "countDistinct",
        format: "number",
      },
    ],
  },

  {
    key: "machineAreaActivity",
    label: "Machine / Area Activity",
    description:
      "Machine and work-area activity using embroidery machine output and production work sessions.",
    category: "machine",
    datasetKey: "machineUtilization",
    defaultColumns: [
      "shift_date",
      "source_module",
      "activity_type",
      "department",
      "machine_or_area",
      "operator_name",
      "total_pieces",
      "total_stitches",
      "session_minutes",
    ],
    defaultDateColumn: "shift_date",
    defaultDatePreset: "last7Days",
    defaultSort: {
      column: "shift_date",
      direction: "desc",
    },
    defaultGrouping: ["source_module", "department", "machine_or_area"],
    defaultAggregations: [
      agg("total_pieces", "sum", "Total Pieces"),
      agg("total_stitches", "sum", "Total Stitches"),
      agg("session_minutes", "sum", "Session Minutes"),
    ],
    defaultVisualization: "bar",
    simpleFilters: [
      "source_module",
      "department",
      "shift",
      "machine_or_area",
      "operator_name",
    ],
    summaryCards: [
      {
        key: "pieces",
        label: "Pieces",
        sourceColumn: "sum_total_pieces",
        function: "sum",
        format: "number",
      },
      {
        key: "stitches",
        label: "Stitches",
        sourceColumn: "sum_total_stitches",
        function: "sum",
        format: "number",
      },
      {
        key: "minutes",
        label: "Session Minutes",
        sourceColumn: "sum_session_minutes",
        function: "sum",
        format: "number",
      },
    ],
  },

  {
    key: "inboundArrivingSoon",
    label: "Inbound Shipments Arriving Soon",
    description: "Inbound shipment lines with upcoming ETA dates.",
    category: "logistics",
    datasetKey: "inboundShipmentActivity",
    defaultColumns: [
      "eta",
      "days_until_eta",
      "inbound_shipment_number",
      "status_label",
      "container_number",
      "forwarder",
      "shipment_type",
      "container_destination",
      "po_number",
      "customer_name",
      "quantity",
      "total_quantity",
      "total_cost",
      "estimated_cost_per_piece",
      "estimated_cost_per_dozen",
      "actual_cost_per_piece",
      "actual_cost_per_dozen",
      "line_carton_count",
      "record_url",
    ],
    defaultDateColumn: "eta",
    defaultDatePreset: "next7Days",
    defaultSort: { column: "eta", direction: "asc" },
    defaultGrouping: ["eta", "status_label"],
    defaultAggregations: [
      agg("inbound_shipment_number", "count", "Shipment Count"),
      agg("quantity", "sum", "Total Quantity"),
      agg("line_carton_count", "sum", "Line Cartons"),
    ],
    defaultVisualization: "bar",
    simpleFilters: [
      "status_label",
      "forwarder",
      "shipment_type",
      "container_destination",
      "customer_name",
      "po_number",
    ],
    summaryCards: [
      {
        key: "shipments",
        label: "Shipments",
        sourceColumn: "count_inbound_shipment_number",
        function: "sum",
        format: "number",
      },
      {
        key: "qty",
        label: "Quantity",
        sourceColumn: "sum_quantity",
        function: "sum",
        format: "number",
      },
      {
        key: "cartons",
        label: "Line Cartons",
        sourceColumn: "sum_line_carton_count",
        function: "sum",
        format: "number",
      },
    ],
  },

  {
    key: "openInboundByStatus",
    label: "Open Inbound Shipments by Status",
    description: "Open inbound shipment lines grouped by status.",
    category: "logistics",
    datasetKey: "inboundShipmentActivity",
    defaultColumns: [
      "status_label",
      "inbound_shipment_number",
      "eta",
      "container_number",
      "forwarder",
      "shipment_type",
      "container_destination",
      "customer_name",
      "po_number",
      "quantity",
      "total_quantity",
      "total_cost",
      "estimated_cost_per_piece",
      "estimated_cost_per_dozen",
      "actual_cost_per_piece",
      "actual_cost_per_dozen",
      "record_url",
    ],
    defaultDateColumn: "eta",
    defaultDatePreset: "last30Days",
    defaultSort: { column: "status_label", direction: "asc" },
    defaultGrouping: ["status_label"],
    defaultAggregations: [
      agg("inbound_shipment_number", "count", "Shipment Count"),
      agg("quantity", "sum", "Total Quantity"),
      agg("line_carton_count", "sum", "Line Cartons"),
    ],
    defaultVisualization: "bar",
    defaultFilters: {
      status_code: { operator: "notIn", values: ["DELIVERED", "RECEIVED_CLOSED"] },
    },
    defaultFilterLogic: "AND",
    simpleFilters: [
      "status_label",
      "forwarder",
      "shipment_type",
      "container_destination",
      "customer_name",
      "po_number",
    ],
    summaryCards: [
      {
        key: "shipments",
        label: "Open Shipments",
        sourceColumn: "count_inbound_shipment_number",
        function: "sum",
        format: "number",
      },
      {
        key: "qty",
        label: "Quantity",
        sourceColumn: "sum_quantity",
        function: "sum",
        format: "number",
      },
      {
        key: "cartons",
        label: "Line Cartons",
        sourceColumn: "sum_line_carton_count",
        function: "sum",
        format: "number",
      },
    ],
  },

  {
    key: "customsHolds",
    label: "Customs Holds",
    description: "Inbound shipments currently marked as customs hold.",
    category: "logistics",
    datasetKey: "inboundShipmentActivity",
    defaultColumns: [
      "eta",
      "days_past_eta",
      "inbound_shipment_number",
      "status_label",
      "container_number",
      "forwarder",
      "container_destination",
      "customer_name",
      "po_number",
      "quantity",
      "total_quantity",
      "total_cost",
      "estimated_cost_per_piece",
      "estimated_cost_per_dozen",
      "actual_cost_per_piece",
      "actual_cost_per_dozen",
      "record_url",
    ],
    defaultDateColumn: "eta",
    defaultDatePreset: "last30Days",
    defaultSort: { column: "eta", direction: "asc" },
    defaultGrouping: ["forwarder", "container_destination"],
    defaultAggregations: [
      agg("inbound_shipment_number", "count", "Shipment Count"),
      agg("quantity", "sum", "Total Quantity"),
    ],
    defaultVisualization: "bar",
    defaultFilters: {
      status_code: { operator: "equals", value: "CUSTOMS_HOLD" },
    },
    defaultFilterLogic: "AND",
    simpleFilters: [
      "forwarder",
      "shipment_type",
      "container_destination",
      "customer_name",
      "po_number",
    ],
    summaryCards: [
      {
        key: "shipments",
        label: "Customs Holds",
        sourceColumn: "count_inbound_shipment_number",
        function: "sum",
        format: "number",
      },
      {
        key: "qty",
        label: "Quantity",
        sourceColumn: "sum_quantity",
        function: "sum",
        format: "number",
      },
    ],
  },

  {
    key: "inboundLineDetailByCustomerPo",
    label: "Inbound Line Detail by Customer / PO",
    description: "Line-level inbound shipment details by customer and PO.",
    category: "logistics",
    datasetKey: "inboundShipmentActivity",
    defaultColumns: [
      "customer_name",
      "po_number",
      "inbound_shipment_number",
      "eta",
      "status_label",
      "logo",
      "tracking",
      "quantity",
      "total_quantity",
      "total_cost",
      "estimated_cost_per_piece",
      "estimated_cost_per_dozen",
      "actual_cost_per_piece",
      "actual_cost_per_dozen",
      "line_carton_count",
      "record_url",
    ],
    defaultDateColumn: "eta",
    defaultDatePreset: "last30Days",
    defaultSort: { column: "customer_name", direction: "asc" },
    defaultGrouping: [],
    defaultAggregations: [],
    defaultVisualization: "datatable",
    simpleFilters: [
      "customer_name",
      "po_number",
      "status_label",
      "container_number",
      "forwarder",
      "shipment_type",
    ],
    summaryCards: [
      {
        key: "rows",
        label: "Lines",
        function: "countRows",
        format: "number",
      },
      {
        key: "qty",
        label: "Quantity",
        sourceColumn: "quantity",
        function: "sum",
        format: "number",
      },
      {
        key: "cartons",
        label: "Line Cartons",
        sourceColumn: "line_carton_count",
        function: "sum",
        format: "number",
      },
    ],
  },

  {
    key: "inboundDestinationSummary",
    label: "Inbound Shipment Destination Summary",
    description: "Inbound quantity and carton totals by destination and status.",
    category: "logistics",
    datasetKey: "inboundShipmentActivity",
    defaultColumns: [
      "container_destination",
      "status_label",
      "quantity",
      "line_carton_count",
    ],
    defaultDateColumn: "eta",
    defaultDatePreset: "last30Days",
    defaultSort: { column: "container_destination", direction: "asc" },
    defaultGrouping: ["container_destination", "status_label"],
    defaultAggregations: [
      agg("inbound_shipment_number", "count", "Shipment Count"),
      agg("quantity", "sum", "Total Quantity"),
      agg("line_carton_count", "sum", "Line Cartons"),
    ],
    defaultVisualization: "bar",
    simpleFilters: [
      "container_destination",
      "status_label",
      "forwarder",
      "shipment_type",
      "customer_name",
    ],
    summaryCards: [
      {
        key: "shipments",
        label: "Shipments",
        sourceColumn: "count_inbound_shipment_number",
        function: "sum",
        format: "number",
      },
      {
        key: "qty",
        label: "Quantity",
        sourceColumn: "sum_quantity",
        function: "sum",
        format: "number",
      },
      {
        key: "cartons",
        label: "Line Cartons",
        sourceColumn: "sum_line_carton_count",
        function: "sum",
        format: "number",
      },
    ],
  },

  {
    key: "pastEtaNotDelivered",
    label: "Past ETA / Not Delivered",
    description: "Inbound shipments past ETA that are not delivered or closed.",
    category: "logistics",
    datasetKey: "inboundShipmentActivity",
    defaultColumns: [
      "eta",
      "days_past_eta",
      "inbound_shipment_number",
      "status_label",
      "container_number",
      "forwarder",
      "container_destination",
      "customer_name",
      "po_number",
      "quantity",
      "total_quantity",
      "total_cost",
      "estimated_cost_per_piece",
      "estimated_cost_per_dozen",
      "actual_cost_per_piece",
      "actual_cost_per_dozen",
      "record_url",
    ],
    defaultDateColumn: "eta",
    defaultDatePreset: "last30Days",
    defaultSort: { column: "days_past_eta", direction: "desc" },
    defaultGrouping: ["status_label", "forwarder"],
    defaultAggregations: [
      agg("inbound_shipment_number", "count", "Shipment Count"),
      agg("days_past_eta", "avg", "Average Days Past ETA"),
    ],
    defaultVisualization: "bar",
    defaultFilters: {
      days_past_eta: { operator: "numberRange", from: 1 },
      status_code: { operator: "notIn", values: ["DELIVERED", "RECEIVED_CLOSED"] },
    },
    defaultFilterLogic: "AND",
    simpleFilters: [
      "status_label",
      "forwarder",
      "shipment_type",
      "container_destination",
      "customer_name",
      "po_number",
    ],
    summaryCards: [
      {
        key: "shipments",
        label: "Past ETA",
        sourceColumn: "count_inbound_shipment_number",
        function: "sum",
        format: "number",
      },
      {
        key: "avgPast",
        label: "Avg Days Past",
        sourceColumn: "avg_days_past_eta",
        function: "avg",
        format: "number",
      },
    ],
  },

  {
    key: "recentlyDeliveredClosedInbound",
    label: "Recently Delivered / Closed Shipments",
    description: "Inbound shipments recently delivered or received/closed.",
    category: "logistics",
    datasetKey: "inboundShipmentActivity",
    defaultColumns: [
      "updated_at",
      "inbound_shipment_number",
      "status_label",
      "container_number",
      "forwarder",
      "container_destination",
      "customer_name",
      "po_number",
      "quantity",
      "total_quantity",
      "total_cost",
      "estimated_cost_per_piece",
      "estimated_cost_per_dozen",
      "actual_cost_per_piece",
      "actual_cost_per_dozen",
      "record_url",
    ],
    defaultDateColumn: "updated_at",
    defaultDatePreset: "last30Days",
    defaultSort: { column: "updated_at", direction: "desc" },
    defaultGrouping: ["status_label", "container_destination"],
    defaultAggregations: [
      agg("inbound_shipment_number", "count", "Shipment Count"),
      agg("quantity", "sum", "Total Quantity"),
    ],
    defaultVisualization: "bar",
    defaultFilters: {
      status_code: { operator: "in", values: ["DELIVERED", "RECEIVED_CLOSED"] },
    },
    defaultFilterLogic: "AND",
    simpleFilters: [
      "status_label",
      "forwarder",
      "shipment_type",
      "container_destination",
      "customer_name",
      "po_number",
    ],
    summaryCards: [
      {
        key: "shipments",
        label: "Delivered / Closed",
        sourceColumn: "count_inbound_shipment_number",
        function: "sum",
        format: "number",
      },
      {
        key: "qty",
        label: "Quantity",
        sourceColumn: "sum_quantity",
        function: "sum",
        format: "number",
      },
    ],
  },

  ...RECUT_REPORT_TEMPLATES,
];

export function getReportTemplate(templateKey: string | null | undefined) {
  if (!templateKey) return null;
  return REPORT_TEMPLATES.find((template) => template.key === templateKey) ?? null;
}

export function getDefaultReportTemplate() {
  return REPORT_TEMPLATES[0] ?? null;
}

export function listReportTemplatesForDataset(datasetKey: string) {
  return REPORT_TEMPLATES.filter((template) => template.datasetKey === datasetKey);
}